### ISSUE TITLE
[Editor] Affected of "Full-Stop With Double-Space"

### ISSUE THREAD

**Issue by marcello-moenkemeyer** [quoid/userscripts#100]
Currently, the editor is affected of the [activated] "full-stop with double-space" shortcut.

As an example for how unwanted this is: It added periods after annotations, thus making them invalid. It took me _hours_ of troubleshooting to finally catch it and distinguish it from space-dots.

_(Irrelevant) System Information:_
> macOS version: macOS Catalina 10.15.7
> Userscripts version: 2.2.1
> Safari version: 14.0.2

**Comment by quoid** [comment]
Thanks for the report. I admit to never having that setting enabled.

I will try to get this resolved for next patch update.
