### ISSUE TITLE
doesn't do anything? and no ui? .....

### ISSUE THREAD

**Issue by Tony1324** [quoid/userscripts#102]
_System Information:_
> macOS version: macOS 11 big sur
> Userscripts version: 3.0.1
> Safari version: 14.0.3

so nothing shows up except one panel that just shows the save location and version
<img width="592" alt="Screen Shot 2021-02-17 at 9 43 21 PM" src="https://user-images.githubusercontent.com/61944932/108297495-58305780-7169-11eb-97de-9ab5a46a68f8.png">

**Comment by quoid** [comment]
@Tony1324 

That is the container app, userscripts safari is a browser extension. **I will update the containing app text in the next version to explain how to get started once installing**.

You're on the right path though:

1) open containing app (as you've done in the in screenshot)

2) click "open in safari extension preferences"

3) enable the extension in the Safari (see screenshot below)

4) after enabled, you should see a new extension button in your browser (see second screenshot below)

5) start using extension

<img width="786" alt="Screen Shot 2021-02-17 at 9 48 48 PM" src="https://user-images.githubusercontent.com/7660254/108298057-49967000-716a-11eb-9baf-3114c721f6ca.png">

<img width="1343" alt="screenshot" src="https://user-images.githubusercontent.com/7660254/108298063-4d29f700-716a-11eb-80e8-c7cb228b9fdb.png">

**Comment by Tony1324** [comment]
ohh ok thanks. for some reason that button didn't appear for me at first

**Comment by quoid** [comment]
@Tony1324 

I've had the same issue and needed to restart safari and manually do into the Safari preferences

It's happened to me with my other extensions as well, so I figure it's Safari related

glad it worked out
