### ISSUE TITLE
Suggestion: Enable/disable relevant scripts from Toolbar icon

### ISSUE THREAD

**Issue by wrigglegb** [quoid/userscripts#103]
I frequently have to turn my userscripts on and off. I made them to prep pages for clipping in cases where my software package’s clipper and my userscripts totally break the site so for each page clipped it’s a change tab, enable two, clip, change tab, disable two, move to the next one.

This isn’t a catastrophe for me but it has highlighted that instead of jumping straight to the editor interface, the toolbar icon could instead (perhaps only on pages where a relevant userscript exists) provide a drop down panel that opens over the page as is common with Safari Extensions.

In my head the list shown would resemble the left column of the editor interface with the names, CSS/JS indicator and on/off toggle for all the scripts relevant to the currently viewed page. Each script could have a button that would open it directly in the editor interface.

I am interested to know if this fits with your vision for Userscripts, and something that might be a part of Userscripts in a future version.

Thanks!

**Comment by quoid** [comment]
Thanks for the comments @wrigglegb 

I have thought about what you are suggesting before. Some other userscript managers do something very close to what you are suggesting. Essentially creating a a dropdown from the toolbar button, or a popover in Apple lingo.

The main reason I have not implemented this yet is because how much work it entails and considering other features, was not as important in previous version updates.

> I am interested to know if this fits with your vision for Userscripts, and something that might be a part of Userscripts in a future version.

Yes. I would like to implement something close to what you've described at some point in the future. However, I am not comfortable giving any sort of timeframe because, as mentioned, it could be quite involved to do that.

> I frequently have to turn my userscripts on and off. I made them to prep pages for clipping in cases where my software package’s clipper and my userscripts totally break the site so for each page clipped it’s a change tab, enable two, clip, change tab, disable two, move to the next one.

Out of curiosity, could you elaborate on what clipping is and your workflow here? I am sure you've already thought of this, but I am wondering if there is a way to work around this without the need for a popover ui in the meantime.

**Comment by quoid** [comment]
@wrigglegb the first iteration of this feature has been implemented in the newest version https://github.com/quoid/userscripts/releases/tag/v3.1.0

Currently it *only* supports disabling *all* script injection from the toolbar popover, but a future will release will enable individual script disable/enable from the popover.

The new version will hopefully be available on the App Store in the coming days, once Apple approves the update.

**Comment by TraderStf** [comment]
I think my suggestion could fit in this thread.
Switch toolbar icon to grey or something else visible when Injection is disabled.
May I suggest a right clic (ctrl clic) on the icon to quickly en/dis-able the Injection.

**Comment by quoid** [comment]
@TraderStf 

> Switch toolbar icon to grey or something else visible when Injection is disabled.

I wish I could make it grey (like the privacy extension apple includes in Safari), but there is no way to control the color of the icon.

It *might* be possible to switch the *actual* icon to something else, but it would still be blue. I will have to look into it more.

> May I suggest a right click (ctrl click) on the icon to quickly en/dis-able the Injection.
 
If this was possible I wouldn't even use a popover :) But unfortunately theres not a way I can find to do this. Even a special entry in the "right click" context menu on the toolbar icon would be nice, if it was possible..

**Comment by TraderStf** [comment]
hihi Apple is locking everything!
Stupid suggestions ;-)
- create 3 new extensions: green, orange and red 🚦
- create a Wirus - Window Insert oveR gUi - draw over the dialog items 🧲

**Comment by TraderStf** [comment]
FYI, ZohoVault free password manager can add a small red icon with a number on the toolbar icon.
Something similar to Apple Mail which shows new emails in the Dock.

**Comment by quoid** [comment]
> FYI, ZohoVault free password manager can add a small red icon with a number on the toolbar icon.
Something similar to Apple Mail which shows new emails in the Dock.

@TraderStf this [option](https://github.com/quoid/userscripts#settings-modal) already exists

<img width="65" alt="Screen Shot 2021-05-17 at 9 07 48 AM" src="https://user-images.githubusercontent.com/7660254/118493876-9220e380-b6ef-11eb-8a44-b30b54068b87.png">

**Comment by TraderStf** [comment]
🤒🤣

**Comment by quoid** [comment]
done: https://github.com/quoid/userscripts/commit/33cb08fcbf2cc101e2263cc4b182ca2e29bdade5

will be released in upcoming version `4.x`
