### ISSUE TITLE
Feature Request: Big Sur style icon

### ISSUE THREAD

**Issue by khaveesh** [quoid/userscripts#109]
The app works perfectly. One minor nitpick is the circular icon. Apple has updated its guidelines for Big Sur app icons to be squircles. For ensuring conformity with the rest of the system, I feel that Userscript's icon must be updated.

I found this work on [macosicons.com](https://macosicons.com): https://media.macosicons.com/parse/files/macOSicons/7045a82441a2ae50f260e60dd5960a90_1608017098667_Userscripts.icns

And I found it nice. You could directly use that since it is under the GPLv3 too.

**Comment by quoid** [comment]
@khaveesh I think this can be accomplished in a  near future update. I am currently working on 3.1 and will attempt to get it in that update.

Would it be possible for you to link an image of what you are posting so I could check it out before downloading it to my local machine?

**Comment by khaveesh** [comment]
![image](https://user-images.githubusercontent.com/4398066/112885889-e3005c80-90ee-11eb-8be0-31048873f381.png)

Here is a preview of the icon. I didn't pull it off correctly, the borders are aliased in this image, but they are proper in the actual icon.

**Comment by quoid** [comment]
Great!

I will use the resources you linked, or something similar, when I push the next update.

Thank you for for the suggestion.

**Comment by quoid** [comment]
@khaveesh the icon as updated in the newest release https://github.com/quoid/userscripts/releases/tag/v3.1.0

the new version will hopefully be available in the coming days, once Apple approves it

thanks again

**Comment by khaveesh** [comment]
Thanks a lot for considering my request. And thanks again for all the work you put into this great extension.
