### ISSUE TITLE
Feature request: option to turn off autoCloseBrackets in code editor

### ISSUE THREAD

**Issue by adbull** [quoid/userscripts#111]
Thanks for this extension, it's really useful! There's one small issue I have, which is that the code editor automatically inserts closing brackets, trailing string quotes, etc. I can imagine it's helpful for many people, but for my editing style I find it usually just gets in the way. Would it be possible to add an option to turn this off?

_System Information:_
> macOS version: 11.2.3
> Userscripts version: 3.0.2
> Safari version: 14.0.3

**Comment by quoid** [comment]
@adbull 

An option can be added for this in the settings area.

I will try to do that for next update.

Thank you for the feedback and suggestion.

**Comment by quoid** [comment]
@adbull this has been added to the new release https://github.com/quoid/userscripts/releases/tag/v3.1.0

this version has been pushed to the app store and will hopefully be available in the coming days
