### ISSUE TITLE
Feature Request: window.close() for windows not created by JavaScript

### ISSUE THREAD

**Issue by unix-fan** [quoid/userscripts#113]
_System Information:_
> macOS version: 10.15.7
> Userscripts version: 3.0.2
> Safari version: 14.0.3

trying to close() a window/tab with userscripts, but getting this in console:
"Can't close the window since it was not opened by JavaScript".
any way to implement overriding this in userscripts?

**Comment by quoid** [comment]
@unix-fan as I am sure you are already aware, that's a javascript limitation, although there might be clever workarounds

> any way to implement overriding this in userscripts?

not through the javascript `window.close()` method, but exposing a custom api, like the [GM api](https://violentmonkey.github.io/api/gm/), to allow users to call the [safari close()](https://developer.apple.com/documentation/safariservices/sfsafaritab/3075410-close) method would be theoretically possible. 

A custom API for userscript users is on my radar. I've done some initial testing and it seems possible, although would likely differ from the GM api.

I can't currently give an accurate estimate as to when something like this would be released, but it *is* on my radar.

**Comment by unix-fan** [comment]
this is not urgent at all, i'm completely fine with "is on my radar" :)

**Comment by quoid** [comment]
> i'm completely fine with "is on my radar" :)

thank you for understanding!

**Comment by quoid** [comment]
@unix-fan next beta release will have custom api methods for `openTab()` and and `closeTab()`

**Comment by quoid** [comment]
merged https://github.com/quoid/userscripts/commit/b8b8a7ff04e8be1d56be0393a5a8369f0a566c8e
