### ISSUE TITLE
nth-last-of-type not colored

### ISSUE THREAD

**Issue by TraderStf** [quoid/userscripts#119]
_System Information:_
> macOS version: 11.2.3 (20D91)
> Userscripts version: 3.1.0
> Safari version: 14.0.3 (16610.4.3.1.7)

The syntax is not colored in ~brown.
For example, first-child is colored but nth-last-of-type(2) is not, it is white. Though it works perfectly.
Number (2 here) is in green and brackets are white

**Comment by quoid** [comment]
Thank you for the report. In the future, if possible,  please provide visual references to the style/visual bugs.

> For example, first-child is colored but nth-last-of-type(2) is not, it is white. Though it works perfectly.

Codemirror assigns pseudo classes with and without parenthesis different class names. I am ok with them looking different.

<img width="551" alt="Screen Shot 2021-04-26 at 9 12 11 AM" src="https://user-images.githubusercontent.com/7660254/116088073-85b8e600-a66f-11eb-9d80-c12fa955e4e7.png">
