### ISSUE TITLE
App says "Safari Extension Disabled" bug

### ISSUE THREAD

**Issue by TraderStf** [quoid/userscripts#120]
_System Information:_
>macOS version: 11.2.3 (20D91)
>Userscripts version: 3.1.0
>Safari version: 14.0.3 (16610.4.3.1.7)

Launch the App, it shows a red dot and "Safari Extension Disabled"
Though it is enabled, opening the US script window does not change the problem.
Disable then re-enable the extension neither.
Quite-Relaunch Safari neither

**Comment by quoid** [comment]
I've witnessed this as well, next update will need to some attention paid to this.

**Comment by TraderStf** [comment]
Seems solved with macOS 11.3.1
I did not check with os 11.3.

**Comment by quoid** [comment]
Thank you for the update, I already made some improvements on a new branch, but I was having trouble pin pointing the cause of the issue. Perhaps it was os related.
