### ISSUE TITLE
Suggestion: JS/CSS Templates

### ISSUE THREAD

**Issue by TraderStf** [quoid/userscripts#122]
_System Information:_
> macOS version: 11.2.3 (20D91)
> Userscripts version: 3.1.0
> Safari version: 14.0.3 (16610.4.3.1.7)

Add few templates (samples) that can be used by average users, in order also to show best practices.
Few examples of some "requirements" to avoid problems. You get the idea :-)

if (window === window.top)
if (window.location)
if (location.protocol != 'https:') exit();

catch (exception)
    {
        console.error(exception);
        return;
    }

**Comment by quoid** [comment]
I think the onus should be on the user to have certain level of code & scripting experience before using the extension. I am not very keen on this idea, outside of basic guidance in the README.

If there are specific README directions you'd like to see, please re-open the issue with clear suggestions as to what to add.

Thanks

**Comment by TraderStf** [comment]
The idea was to provide a very small frame/base for intermediate users, rookies like me.
Making small codes to do this or that is one thing, in JS, adding few "advanced" lines to correctly interact with more complex parts like exceptions, error reporting to user or console, start the code by a function or directly type my garbage...
I don't know if I am clear :-)

For example, a basic Frame, CCC is the code you, Justin, will provide in the frame.

```
function()
{
CCC

/* insert user code here*/

   catch (exception)
   {
       CCC
       /* insert extra user error handling here */
   }
CCC
}
```

rather than

`my user code without nothing before or after, without your CCC`

**Comment by TraderStf** [comment]
Here is an example, nothing to do of course with US, but that example is what I have in mind.

https://developers.google.com/web/fundamentals/architecture/app-shell#example-html-for-appshell
