### ISSUE TITLE
Suggestion: New Category - Tag Cleaner

### ISSUE THREAD

**Issue by TraderStf** [quoid/userscripts#123]
_System Information:_
> macOS version: 11.2.3 (20D91)
> Userscripts version: 3.1.0
> Safari version: 14.0.3 (16610.4.3.1.7)

Like we have now CSS, JS and Remote, a Tag one.
To easily fill tags, trackers.

FROM
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiStOCCxp7wAhXywAIHHc5YCqEQFjAVegQIAxAD&url=https%3A%2F%2Ffr.wikipedia.org%2Fwiki%2FZebra&usg=AOvVaw2JbNgAG2IKPIpikhgffHot
TO
https://fr.wikipedia.org/wiki/Zebra

User-defined can be added.

Import ALL CSV files from a predefined folder. 1 file per domain?

Some are really simple, wired.com, you zap everything, just keep ~location origin+path

**Comment by quoid** [comment]
I am sorry, I do not understand this feature request, can you be more explicit in what you are asking?

**Comment by TraderStf** [comment]
It can be closed, as US is intended for advanced users, see our other thread.
It was some kind of table view where you enter the tag you want to be deleted, fake e.g.

google.*  rct   cad   uact
amazon.*   abc   ref   xyz  mno  def
...

Is it possible to clean/edit the URL before the page content is opened/loaded?

If I click on link with tracking tags and just remove them afterwards, the site get all the info already before the tags get removed.

**Comment by quoid** [comment]
> Is it possible to clean/edit the URL before the page content is opened/loaded?

It is not possible with this extension. The earliest timing is at `document-start`.

It may be possible with this Safari App Extension API [method](https://developer.apple.com/documentation/safariservices/sfsafariextensionhandling/3238031-page), but implemented a way to access that method from Userscripts is currently outside the scope of what I am aiming to provide, but maybe in the future.
