### ISSUE TITLE
Suggestion: Extra Functions

### ISSUE THREAD

**Issue by TraderStf** [quoid/userscripts#124]
_System Information:_
> macOS version: 11.2.3 (20D91)
> Userscripts version: 3.1.0
> Safari version: 14.0.3 (16610.4.3.1.7)

Some cleaned functions, without having to deal with dozen of libraries.
For example: get the domain.
It is very difficult, must take care of sub-domains, new tld: .co.uk - .lawyers - .XN...

Several codes are available already:
https://publicsuffix.org/
https://publicsuffix.org/learn/

https://publicsuffix.org/list/public_suffix_list.dat

https://github.com/publicsuffix/list

https://github.com/oncletom/tld.js
https://github.com/gorhill/publicsuffixlist.js

https://data.iana.org/TLD/tlds-alpha-by-domain.txt

**Comment by quoid** [comment]
The user can use a wildcard selector (`*`), this is covered in the [match pattern section of the README](https://github.com/quoid/userscripts#metadata).

**Comment by TraderStf** [comment]
It is the domain as a "variable", not as @match.
UserScripts app would include the extra function Userscript_getrealdomain()
This example is to get the real domain as it is a nightmare to find it, see provided links.
Probably other complex functions could be integrated in US, rather than reinvent the wheel each time.

e.g.
```
thedomain = Userscript_getrealdomain(location.hostname);

if (thedomain != "ibm.co.uk")
{

}
```

**Comment by quoid** [comment]
I believe this is already covered in this issue: https://github.com/quoid/userscripts/issues/113
