### ISSUE TITLE
Suggestion: Open button as a link?

### ISSUE THREAD

**Issue by TraderStf** [quoid/userscripts#127]
_System Information:_
> macOS version: 11.3 (20E232)
> Userscripts version: 3.1.0
> Safari version: 14.1 (16611.1.21.161.3)

If the Open button was a link would it respect Safari Keyboard shortcuts when you click on it?
For example, open in tab/window (bring to front) if key cmd-opt-shit... is pressed.

Goal: reopen it as it was close: window size and position, or at least not as a tab.

Or perhaps it is possible to modify US own window by a "self-javascript" ?

**Comment by TraderStf** [comment]
Also, if window is empty, do not open a new tab/window.

Where can I send you few $

**Comment by quoid** [comment]
There are some limitations to opening the extension's bundled HTML page. The options are to open a new window or tab, I prefer tab. There is no advanced functionality that can implemented other than that. The API doesn't even allow for any reasonable way to detect if the page is *already* open, I had make a ["hack"](https://github.com/quoid/userscripts/blob/3ca6c937a429435995315a3db1932e820bfa2c39/extension/Userscripts%20Extension/Functions.swift#L70) to try and detect it, and even that is not super reliable.

There is not a reliable way to detect empty windows, windows showing custom "new tab" pages or start pages.

**Comment by quoid** [comment]
Closing due to inability to satisfy request
