### ISSUE TITLE
Can this stop-cookie-consent be made in US?

### ISSUE THREAD

**Issue by TraderStf** [quoid/userscripts#130]
Hello,
This code is too complex for my JS knowledge, can it be made with US.
https://github.com/privacycloud/consent-manager-web-ext
Thanks

**Comment by TraderStf** [comment]
OK forgot about it...

List of DIV and CLASS to block cookie consent dialogs:
https://github.com/search?q=cookie+consent+block

Works very well all browsers, even ß in Safari, and has white list! Nice options too.
https://ninja-cookie.com/fr/

**Comment by quoid** [comment]
@TraderStf for more general questions/comment like this, please email me rather than opening an issue
