### ISSUE TITLE
Cannot Add More than 9 scripts! 

### ISSUE THREAD

**Issue by Kartik-715** [quoid/userscripts#131]
_System Information:_
> macOS version: 11.3
> Userscripts version: Version 3.1
> Safari version: 14.1

There seems to be some problem when I try and save more than 9 script, For some reason script injection stops and I can't use any of the scripts! Is this a bug?

**Comment by quoid** [comment]
@Kartik-715 Did you figure out what the problem was?

**Comment by Kartik-715** [comment]
Hey! I'm sorry! It was some error with the meta-data in the script I was adding!
Just a suggestion: There should be at least some sort of warning/error in console/anywhere that a script cannot be parsed, So that it can be rectified!

**Comment by quoid** [comment]
I am glad it was sorted!

> Just a suggestion: There should be at least some sort of warning/error in console/anywhere that a script cannot be parsed, So that it can be rectified!

I agree. This was suggested in [the past](https://github.com/quoid/userscripts/issues/80#issuecomment-700943050) and started on it, but never finished. I will make a new issue for this.
