### ISSUE TITLE
Unable to fetch content from local server

### ISSUE THREAD

**Issue by sumanth-98-dev** [quoid/userscripts#137]
This is my userscript
```
// ==UserScript==
// @name        NewScript-9rxax5d2
// @description This is your new file, start writing code
// @match https://simply-how.com/*

// ==/UserScript==
(function(){

     // start edit
      var xhr = new XMLHttpRequest();
     console.info('working fine')
     xhr.open("GET", 'http://localhost:8034', true); //The localhost webserver runs some complex curl commands to fetch resources elsewhere.
     xhr.onload = function(response) {
         console.log(response)

     }
     xhr.send()
})();
```

I'm facing this error.
```
[blocked] The page at https://simply-how.com/category/for-geeks was not allowed to display insecure content from http://localhost:8034/
Not allowed to request resource
XMLHttpRequest cannot load http://localhost:8034/ due to access control checks.
```
![Screenshot 2021-06-08 at 10 51 21 PM](https://user-images.githubusercontent.com/24863030/121229856-1f4cf780-c8ac-11eb-9cdf-b24544914265.png)

The same userscript works fine in tampermonkey in Firefox. Any ideas? Thanks

**Comment by quoid** [comment]
@sumanth-98-dev 

Can you provide an example that is loading from a local server?

**Comment by quoid** [comment]
For example

```js
// ==UserScript==
// @name        New script - k21p.com
// @match       https://www.k21p.com/
// @version     1.0
// ==/UserScript==

(function(){

     // start edit
     var xhr = new XMLHttpRequest();
     console.info('working fine')
     xhr.open("GET", 'https://www.k21p.com', true);
     xhr.onload = function(response) {
         console.log(response)

     }
     xhr.send()
})();
```

The above `xhr` works as expected. You might run into CORS issues though.

**Comment by sumanth-98-dev** [comment]
@quoid In my python webserver running in localhost, I've added CORS headers.
```
self.send_header('Access-Control-Allow-Origin', "*");
self.send_header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
self.send_header('Access-Control-Allow-Headers', 'Content-Type');
```
If I don't add these headers, firefox doesn't work. Safari is failing irrespective of these headers. 
Your example works fine because there's no cross origin request. If we use localhost in your example, it gives the same error I'm facing.
Is there anyway I can override Safari's behaviour? Thanks

**Comment by quoid** [comment]
@sumanth-98-dev

> Your example works fine because there's no cross origin request. 

I can change the domain for the `xhr` and it will work, as you've pointed out, if the domain allows cross origin requests.

```js
// ==UserScript==
// @name        New script - filmgarb.com
// @match       https://www.filmgarb.com/
// @version     1.0
// @description foo
// ==/UserScript==

(function(){

     // start edit
     var xhr = new XMLHttpRequest();
     console.info('working fine')
     xhr.open("GET", 'https://www.k21p.com', true);
     xhr.onload = function(response) {
         console.log(response)

     }
     xhr.send()
})();
```

I am not sure why it is not working with you, but I don't think it is an issue with the extension, but rather something with the local server and/or an inherit aspect of cross origin requests and safari.

I am going to close this issue. If you find it *is* an issue with the extension, feel free to reopen and report.

**Comment by sumanth-98-dev** [comment]
I've figured this out. The localhost server should be HTTPS not HTTP.
