### ISSUE TITLE
Test v1.1.0

### ISSUE THREAD

**Issue by quoid** [quoid/userscripts#14]
*in progress*

Encountered issues:

- `UserDefaults` isn't created at first launch, so forced to click toggle on first use
  - options to fix:
      - change [this line](https://github.com/quoid/userscripts/blob/a20cb6f4be05901717ffa7231979913ec24a56c6/Userscripts%20Extension/SafariExtensionHandler.swift#L19) to `!= "off"`
    - create `UserDefaults` on first launch

**Comment by gingerbeardman** [comment]
Are the recent changes from user feedback, Apple or self-assigned?

**Comment by quoid** [comment]
Mostly self assigned, but got the idea for a toggle `on/off` from a friend who is using it currently

**Comment by quoid** [comment]
1.1.0 seems good, I will be pushing updates today
