### ISSUE TITLE
Doesn't work at all anymore on Mojave

### ISSUE THREAD

**Issue by julian-weinert** [quoid/userscripts#141]
I don't like these kinds of issue reports, but I don't know what else to say.
Just a few minutes ago I installed the last update (from 5 days ago) and the script injection completely stopped working.

I couldn't get any logs on any page. Please let me know if I can somehow gather more helpful information.

_System Information:_
> macOS version: 10.14.6 (18G8022)
> Userscripts version: 3.2.0
> Safari version: 4.0.3 (14610.4.3.1.7)

**Comment by quoid** [comment]
@julian-weinert 

 > I don't like these kinds of issue reports, but I don't know what else to say.

If you could provide more detail on what isn't working, that would be helpful. Is it the UI? Script injection?

You mentioned something about logs, so I imagine it is script injection, but I am just guessing.

If it is script injection, it helps to get an example of a real userscript that does not work for you. Most of the time I can quickly figure out what is going wrong just by seeing that.

**Comment by quoid** [comment]
@julian-weinert 

In [version 3.2](https://github.com/quoid/userscripts/releases/tag/v3.2.0) the way `@match` works changed, that could have something to do with your issue.

**Comment by julian-weinert** [comment]
Oh, thanks for the quick reply. Following your comment I tried it using `// @include         *://*/*` in the header and `console.log('HELLO');` as test in the first line.

Doesn't come through. Still not 100% sure if I got it right, but I do think so

**Comment by quoid** [comment]
@julian-weinert can you link the entire userscript and tell me what `url` you are trying on? that match pattern seems valid to me.

here's a simple test script:

```js
// ==UserScript==
// @name        TestScript
// @description This is your new file, start writing code
// @match       *://*/*
// ==/UserScript==

console.log("This is a test script");
```

**Comment by julian-weinert** [comment]
Good lord am I stupid. During my test I disabled the script and couldn't see my changes actually "worked"
Now I'm getting the total wildcard to work (as in your test script, which works as well).

I'm trying to run against google images and YouTube. The images one comes from here https://gist.githubusercontent.com/bijij/58cc8cfc859331e4cf80210528a7b255/raw/viewimage.user.js but after you pointed me to the matching I see that it won't work. This is my attempt for now
```JavaScript
// @include         *://*google.*/search*tbm=isch*
// @include         *://*google.*/imgres*
```

The YT one should match any youtube URL and can be found here https://gist.github.com/julian-weinert/425fa15d7117785e84cad6fbf8df460c

**Comment by julian-weinert** [comment]
Also completely ignoring the host does not work properly: `*://*/search*tbm=isch*`

**Comment by quoid** [comment]
> The YT one should match any youtube URL and can be found here https://gist.github.com/julian-weinert/425fa15d7117785e84cad6fbf8df460c

Issues:

- `*://*.youtube.*` 
  - wildcards can't be used (currently) on tlds (com, net, etc..) as per the [docs](https://developer.chrome.com/docs/extensions/mv3/match_patterns/), specifically note the part that says `If '*' is in the host, it must be the first character`
  - a `path` **must** be included
  - **Fix:** `*://*.youtube.com/*`

- `*://*.youtu.be*`
  - a `path` **must** be included
  - this pattern would have been valid pre version 3.2!
  - **Fix:** `*://*.youtu.be/*`

**Comment by quoid** [comment]
Also note, that the author of the google script is using `@include` which for this extension is a fallback to `@match`. `@include` has a slightly different syntax.

**Comment by quoid** [comment]
@julian-weinert the google images one is harder to work around because matching only happens on the protocol, host and path, not the full url (which is utilized in the userscript).

There's ways around this in the actual code, but it will take some work to fork it and update the code for an additional check.

If `@include` is implemented into the extension it  will open more possibilities, but it is not currently supported and might be a little bit before it is supported.

**Comment by julian-weinert** [comment]
Oh, that's pretty sad, since it did support that in the past.

Problem is that google as well as many other pages is not US-exclusive... Meaning I will need to add a `@match` statement for any TLD in existence, since I don't know what google owns and what not.
Google is the problem that the image search URL does not differ from any other search.

Meaning all this pattern matching is now pretty useless and I will need to include the script in any page and code the rest up in JavaScript.

May I ask out of interest why you chose to remove so much functionality? Feels like a big step backwards to me

**Comment by julian-weinert** [comment]
Oh and big thanks for your prompt help!

**Comment by quoid** [comment]
@julian-weinert 

I'll try to implement '@include' properly this week for more versatility with match patterns. 

That'll allow for wildcard matching against full urls. 

Sign up for the beta if you'd like to get the build early.

**Comment by quoid** [comment]
@julian-weinert You can read more about the rationale for the change here https://github.com/quoid/userscripts/issues/107

**Comment by julian-weinert** [comment]
Thanks again!

**Comment by quoid** [comment]
@julian-weinert 

Version 3.3.0 beta is available and now supports regular expressions and glob patterns for`@include` and `@exclude`.

I tested the Google Images userscript and it seemingly works with a minor change:

```js
// @include         http*://*.google.*/search*tbm=isch*
// @include         http*://*.google.*/imgres*
```

the `tld` suffix in any patterns or expressions is not currently supported but using the glob pattern `*` wildcard in `@include` does now work as you'd expect (and you can use it anywhere you'd like).  [Read more here](https://wiki.greasespot.net/Include_and_exclude_rules)

Let me know if you'd like the beta build so you won't have to wait for this feature. I am going to test it for a short while to ensure everything is currently working.
