### ISSUE TITLE
WebExtension Port

### ISSUE THREAD

**Issue by quoid** [quoid/userscripts#145]
Port extension to [Safari WebExtension API](https://developer.apple.com/documentation/safariservices/safari_web_extensions)

- [x] non-persistent background page
- [x] popup with rich functionality
    - [x] toggle injection
    - [x] toggle individual scripts
    - [x] update all scripts in scripts folder
    - [x] update individual scripts in scripts folder
    - [x] open scripts folder
    - [x] popup badge
    - ~~access settings~~
- [x] port page editor
- [x] code refactoring/cleanup
- [x] review `TODO`s in files

**Comment by quoid** [comment]
related: https://github.com/quoid/userscripts/commit/33cb08fcbf2cc101e2263cc4b182ca2e29bdade5

**Comment by naturale0** [comment]
I'd be more than happy to join if you are planning to distribute the iOS/iPadOS version via TestFlight.

**Comment by quoid** [comment]
@naturale0 The port is mostly done and a beta version is available for desktop, but it is not yet available for iOS. I need to read up and figure out how to enable usage in iOS and ipadOS.
