### ISSUE TITLE
Use tabs.insertCSS() for css injection

### ISSUE THREAD

**Issue by quoid** [quoid/userscripts#151]
Must wait until `cssOrigin` in supported in Safari so it can be set to `user` and override all page styling. Otherwise it would need a lot of `!important` values.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/insertCSS

**Comment by quoid** [comment]
version `4.2` will use this for css injection even though `cssOrigin` is still not supported. The requirement to use `!important` exists even when using the the [current method](https://github.com/quoid/userscripts/blob/16a23bd5ea94f9bacbc9a09a21b3ddb779c41d65/extension/Userscripts%20Extension/Resources/content.js#L25) so that should not deter this change. Further, `insertCSS` seems less affected by strict CSPs, which something that we can't get around with the current implementation.

**Comment by quoid** [comment]
done in https://github.com/quoid/userscripts/commit/a7cb56267ce9e52fb302cbd1913ae25fd225463d

**Comment by lslqtz** [comment]
After the 4.2 (macOS)/1.2 (iOS) version update, my CSS needs a lot of !important to work properly, and I cannot modify the window in the same iframe :(. (Open the iframe page independently to work properly)
But I'm not sure if it has anything to do with this updated change.

**Comment by quoid** [comment]
@lslqtz 

>m y CSS needs a lot of !important to work properly

It is probably related to the updated. I didn't wait for `cssOrigin` to implement this. Unfortunately Safari still does not support that so `!important` values will be needed, unless you construct the css in a way to circumvent that.

Until that is supported, this will be the case. Hopefully they update their APi soon.

> But I cannot modify the window in the samesite iframe :(. (Open the iframe page independently to work properly),

I do not understand this, can you clarify?

**Comment by quoid** [comment]
@lslqtz 

I see the bug with iframes: https://github.com/quoid/userscripts/issues/268
