### ISSUE TITLE
Distribution of WebExtension Directly to Users

### ISSUE THREAD

**Issue by quoid** [quoid/userscripts#154]
It is no longer possible to, conveniently, distribute Safari extension directly to users. In the infinite wisdom of the Apple overlords, they've decided:

> [Distribution to end users for Safari Web Extensions is limited to the Mac App Store. You can test Safari Web Extensions distributed with a notarized app by using the Allow Unsigned Extensions option from the Develop Menu.](https://developer.apple.com/forums/thread/659029)

The "Allow Unsigned Extensions" setting does **not** persist between browser startups. Users must enable that setting every single time they start Safari. 

This could change how releases are distributed through this repo for versions 4+.

Hopefully this changes in the near future, until then I will keep this issue open as reminder.

**Comment by TraderStf** [comment]
Not sure I get it all.

But even with Allow selected US does not appear in the Extensions.

If it is "normal" don't waste your time answering.

Have a nice sunday.

Stéphane

**Comment by quoid** [comment]
@TraderStf It'r not normal, you should be seeing it. I am going to send you an email to try an work it out

**Comment by mikigal** [comment]
Do you think about releasing beta version using Apple's Testflight?
I guess then we don't need to re-enable Allow Unsigned Extensions every Safari restart

**Comment by quoid** [comment]
@mikigal i was under the impression TestFlight was iOS only. Is it available for macOS now?

**Comment by mikigal** [comment]
Hmm, I was always sure that it's supported on every platform. But if not, it's good idea for testing after beta release of mobile version

**Comment by quoid** [comment]
@mikigal looks like it will available this fall but it's not currently. https://developer.apple.com/videos/play/wwdc2021/10170/

**Comment by quoid** [comment]
closing since Testflight is now being used

**Comment by keycommander** [comment]
Very nice conceptually how do I try it out?

**Comment by anhtai9710** [comment]
Ghjgfv
