### ISSUE TITLE
Extension Enabled Dot Not Updating

### ISSUE THREAD

**Issue by kfatehi** [quoid/userscripts#155]
It should update after app window focus, but it is not.

<img width="481" alt="Screen Shot 2021-08-14 at 4 01 53 PM" src="https://user-images.githubusercontent.com/175305/129462241-3ba20c27-af30-4dd5-9f95-fd574de541f3.png">

**Comment by quoid** [comment]
merged https://github.com/quoid/userscripts/commit/b8b8a7ff04e8be1d56be0393a5a8369f0a566c8e
