### ISSUE TITLE
Please Add iCloud Syncing

### ISSUE THREAD

**Issue by gitatmax** [quoid/userscripts#156]
_System Information:_
NA (feature request)

**Comment by quoid** [comment]
@gitatmax 

You can choose any folder you'd like to store your userscripts. Personally I use my iCloud folder which syncs across my Apple devices.

See [here for more details](https://github.com/quoid/userscripts#save-location)

**Comment by gitatmax** [comment]
> @gitatmax
> 
> You can choose any folder you'd like to store your userscripts. Personally I use an iCloud drive folder which syncs across my Apple devices.
> 
> See [here for more details](https://github.com/quoid/userscripts#save-location)

Ah, so it is! My mistake for not seeing the option. This'll work great. Closing this issue :)

**Comment by quoid** [comment]
@gitatmax sounds good! thanks!
