### ISSUE TITLE
macOS Userscripts stuck on "Initializing app..." (macOS Monterey PB10)

### ISSUE THREAD

**Issue by v7rzlhb3xg** [quoid/userscripts#160]
_System Information:_
> macOS version: macOS Monterey Beta 10
> Userscripts version: 3.3.1
> Safari version: 15.1
> Is this issue related to script injection? No
> Did the test script (pasted above) successfully run on your machine? N/a

Seems like the latest macOS Monterey beta broke Userscripts although I've only just noticed the problem. Can anyone else on macOS Monterey beta 10 test? No luck with reinstalling the application. 

<img width="1440" alt="Screen Shot 2021-10-16 at 12 18 54 PM" src="https://user-images.githubusercontent.com/18043024/137594776-bf4c6d71-1ffd-4bbc-b8b6-43f570f40061.png">

**Comment by quoid** [comment]
unfortunate, I don't have Monterey yet, but when it comes out I will be pushing version 4 of the macOS app which is built on the web extension api, just waiting for Testflight macOS so I can get testers

**Comment by v7rzlhb3xg** [comment]
@quoid Small update for you on macOS Monterey Release Candidate, console's showing some errors. I suspect this might be a problem in the full release of Monterey next week too if it's happening in RC.
<img width="1440" alt="Screen Shot 2021-10-18 at 4 24 06 PM" src="https://user-images.githubusercontent.com/18043024/137801675-6a92c8b8-e419-4acf-9eb7-de8b9ba95e7b.png">

**Comment by v7rzlhb3xg** [comment]
Looks like it was just some sort of iCloud folder permission issue. After making a new script folder everything is working, sorry to cause any alarm! 
<img width="1255" alt="Screen Shot 2021-10-18 at 6 42 59 PM" src="https://user-images.githubusercontent.com/18043024/137816400-6aee4a15-7c54-4e97-acd4-8509d7757d18.png">

**Comment by quoid** [comment]
@v7rzlhb3xg im glad it's all good now!
