### ISSUE TITLE
@match doesn't allow "?" in the path

### ISSUE THREAD

**Issue by torakoya** [quoid/userscripts#162]
_System Information:_
> macOS version: 11.6.1
> Userscripts version: 3.3.1
> Safari version: 15.1
> Is this issue related to script injection? Yes
> Did the test script (pasted above) successfully run on your machine? Yes

`?` in `@match` doesn't match `?`.

The below userscript should be injected in the pages like https://www.google.com/search?q=foobar , but won't.

```
// ==UserScript==
// @name          TestScript
// @description   This is your new file, start writing code
// @match         *://www.google.com/search?*
// ==/UserScript==

console.log("Hello");
```

**Comment by quoid** [comment]
@torakoya 

The userscript you pasted works for me on google search query pages.

I used the below script to test so the userscript firing was more obvious.

```
// ==UserScript==
// @name          TestScript
// @description   This is your new file, start writing code
// @match         *://www.google.com/search?*
// @run-at        document-start
// ==/UserScript==

console.log(window.location.href);
alert("Hello");
```

**Comment by torakoya** [comment]
@quoid

Hmm, your userscript doesn't work for me.

When I remove the `?`, `@match *://www.google.com/search*`, both your userscript and mine work.

I was reminded that once my userscript had worked, so I tried downgrading this extension to some previous versions, and I found it works on 3.1.0 and doesn't work on 3.2.0.

I hope that will remind you of something.

**Comment by quoid** [comment]
@torakoya 

I forgot to mention, I am on version `4.x` which is not publicly available yet, but as far as I am aware, I have not changed the matching protocol when compared to version `3.3.1`.

In version `3.1.0`, the matching protocol is much different when compared to version `3.2.0+`. I can't say for sure why the userscript works for me and not you.

However if you are encountering issues with `@match`, I would try using [`@include`](https://github.com/quoid/userscripts#metadata) instead. You can get more flexibility with a regex pattern.

**Comment by torakoya** [comment]
@quoid

I built the branch `v4.0.0` from the source code, version 4.0.9, and it worked with the test userscript. I also built the branch `master`, version 3.3.1, and it didn't work. So I think this issue is present only on 3.x, and isn't on 4.x.

Strangely, on version 3.3.1 (both my own build and the App Store build), the test userscript's log "Injecting xxx.js" in the console of Web Inspector doesn't appear, but the userscript increases the badge number of this extension's icon on the Toolbar.

Anyway, I'll use `@include` and wait for the release of version 4.x. Thank you for your help.

Do you have any intention of investigating this issue on version 3.x? If don't, could you close this issue?

**Comment by quoid** [comment]
@torakoya Thank you for checking against version `4.x`, this can help narrow down the issue

> Do you have any intention of investigating this issue on version 3.x? If don't, could you close this issue?

I don't think I will spend time fixing it in version `3.x`, so I will close this ticket, but I appreciate your time and effort debugging. I am glad to hear it's not an issue in version `4.x`
