### ISSUE TITLE
Feature request: GM Value persistence APIs

### ISSUE THREAD

**Issue by SilverEzhik** [quoid/userscripts#167]
Greasemonkey and other user script managers include asynchronous APIs which can be used to save and load string/integer/boolean values:

* [GM.setValue](https://wiki.greasespot.net/GM.setValue)
* [GM.getValue](https://wiki.greasespot.net/GM.getValue)
* [GM.deleteValue](https://wiki.greasespot.net/GM.deleteValue)
* [GM.listValues](https://wiki.greasespot.net/GM.listValues)

This allows creating user scripts which can persist values across websites or allow for configuration by the user without modifying the script source. For example, I could add a checkbox to temporarily enable debug output in my script and have that change persist across page reloads and domain changes. 

I think this is the only feature I'm missing, absolutely loving using this on iOS otherwise :). Being able to point the userscripts folder to cloud storage and having everything automatically update as I edit scripts from my PC is a godsend.

**Comment by quoid** [comment]
Thanks for the request @SilverEzhik - adding additional `GM` api methods are next on the list (after getting these current versions released).

**Comment by quoid** [comment]
@SilverEzhik newest iOS and macOS builds will have these methods exposed to the user

**Comment by SilverEzhik** [comment]
Awesome, I can confirm that it works with my scripts, though it looks like `@grant` only checks for `GM_` and not `GM.`

Also, taking a quick look at the source, it looks like `GM_` and `GM.` variants are identical, but there's actually a difference between the two since `GM_` variants are synchronous while `GM.` variants are supposed to be asynchronous. This is fine for me since I've already been using asynchronous variants, but if backwards compatibility is a concern, it might be better to remove `GM_` variants and leave a note in the documentation pointing to async variants.

Here's a relevant discussion for a different user script manager with a similar issue: https://github.com/erosman/support/issues/98

**Comment by SilverEzhik** [comment]
By the way, Violentmonkey has a good reference of the myriad of `GM` APIs: https://violentmonkey.github.io/api/gm

**Comment by quoid** [comment]
@SilverEzhik 

> Also, taking a quick look at the source, it looks like GM_ and GM. variants are identical, but there's actually a difference between the two since GM_ variants are synchronous while GM. variants are supposed to be asynchronous. This is fine for me since I've already been using asynchronous variants, but if backwards compatibility is a concern, it might be better to remove GM_ variants and leave a note in the documentation pointing to async variants.

Thank you very much for this info. I had no idea of these differences. I think considering this, I will remove the `GM_` variants and update `@grant` to check for `GM.`. If backwards compatability is desired, the old `GM_` variants can always be added in at a later date.

Thanks again

**Comment by quoid** [comment]
merged https://github.com/quoid/userscripts/commit/b8b8a7ff04e8be1d56be0393a5a8369f0a566c8e
