### ISSUE TITLE
QUESTION: How to use @require

### ISSUE THREAD

**Issue by ThatXliner** [quoid/userscripts#168]
So I know that the `@require` field can be used to download JavaScripts from, say, CDNs. Do we use es6 `import`s or `require` or what?

**Comment by quoid** [comment]
@ThatXliner 

Here's a metadata example:

```js
// ==UserScript==
// @name            ThatXliner TestScript 
// @description     Test script for ThatXliner
// @match           <all_urls>
// @require https://code.jquery.com/jquery-3.5.1.min.js
// @noframes
// ==/UserScript==

console.log($("body"));
```

Include the library with `@require` and use it as you would if you were to include in the `<head>` of your webpage. IN the example userscript above, if you visit https://www.k21p.com/ you should see the `body` element in your browser console.
