### ISSUE TITLE
Latest update (4.0.9 build 31) breaks some userscripts with error 'SyntaxError: JSON Parse error: Unexpected identifier "object"'

### ISSUE THREAD

**Issue by v7rzlhb3xg** [quoid/userscripts#169]
Seems like the latest update is stopping these two from working at all, both on macOS and iOS/iPadOS. I've reverted to 4.0.9 (30) in the meantime.

Here's the two scripts in question:
https://github.com/KevinParnell/OneeChan
https://github.com/ccd0/4chan-x

And here's what the Javascript console spit out, hope it's helpful!

<img width="1440" alt="Screen Shot 2021-11-22 at 10 37 51 AM" src="https://user-images.githubusercontent.com/18043024/142891657-06e1aa93-72ac-436f-a8fd-3cf596f2fcf2.png">

_System Information:_
> macOS version: Monterey 12.0.1
> Userscripts version: macOS: 4.0.9 (31), iOS/iPadOS: 0.1 (3)
> Safari version: 15.1

Let me know if you need any more information or testing.

**Comment by quoid** [comment]
@v7rzlhb3xg I think both of these issues are related to what @SilverEzhik mentioned in #167 

I used in correct method names for the asynchronous `GM.` methods. Both of the userscripts you linked are looking to use `GM_setValue` and associated methods. However in my recent update those methods are asynchronous. In short, I need to remove the `GM_` methods while keeping the `GM.` methods and in the future possible implement the synchronous `GM_` methods. 🤯

**Comment by v7rzlhb3xg** [comment]
Everything seems to be working again, thanks!

**Comment by quoid** [comment]
@v7rzlhb3xg awesome, *thank you* for updating!
