### ISSUE TITLE
Content Security Policies Issues

### ISSUE THREAD

**Issue by quoid** [quoid/userscripts#17]
Certain websites with strict content security policies will not allow the injected script to run.

console error:

`Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy`

This will likely be the case for any website with strict policies but here are some examples:

- https://github.com
- https://csp.withgoogle.com/docs/adopting-csp.html

The major issue here is that unlike legacy versions of Safari extension, this extension is not [dynamically creating content scripts](https://developer.apple.com/documentation/safariextensions/safariextension/1635517-addcontentscript), that *does not* seem possible any more. Rather it is saving the javascript locally, [then injecting it into the webpage, and immediately executing it](https://github.com/quoid/userscripts/blob/master/Userscripts%20Extension/script.js).

It will have to investigated whether or not there is a better way to inject the script and execute the code to circumvent the CSP (I don't like this idea) or to figure out whether or not content scripts in this new format can be dynamic.

**Comment by quoid** [comment]
"easy" fix would be for the content script to read from the saved script, and rather than injecting it into the webpage, parse it and run it - doing this with `eval()` is easy and seemingly works as intended.

Considering [eval() is evail](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#Do_not_ever_use_eval!), I would be curious some others' thoughts.

@kfatehi, @gingerbeardman?

**Comment by gingerbeardman** [comment]
I wonder how other GitHub modifying scripts and extensions do it?

**Comment by quoid** [comment]
> I wonder how other GitHub modifying scripts and extensions do it?

I am guessing they are putting the code directly into the content script, I can't find the source to zenhub or something similar but that would be the most effective approach.

Essentially that what this new technique would do, but it'd be dynamic. I was talking with @kfatehi yesterday and I think using a [new function constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) would be a good alternative than eval() as it's better performing. Initial test show it working as intended and possibly even a bit better performing that the previous method - not to mention it fixes the CSP issue.

**Comment by gingerbeardman** [comment]
Here's one (Chrome/Firefox) https://github.com/sindresorhus/refined-github

**Comment by quoid** [comment]
Thanks for the link!

Looks like they are injecting as I thought - [link](https://github.com/sindresorhus/refined-github/blob/88d888d91d35f4b071c4ea0cae3105828541e136/source/manifest.json#L43). If the domains that require the script are static, it's much easier to avoid CSP issues.

Solution will be forthcoming!

**Comment by quoid** [comment]
resolved in the above commit

**Comment by gingerbeardman** [comment]
Wow 1.2.0 hit the MAS quickly!
