### ISSUE TITLE
@require ignores urls not ending in .js

### ISSUE THREAD

**Issue by Taxyovio** [quoid/userscripts#179]
I’ve not been able to make this [Manga Loader NSFW](https://sleazyfork.org/en/scripts/12657-manga-loader-nsfw) script work. This script is a NSFW add-on to the [main script](https://greasyfork.org/en/scripts/692-manga-loader). It uses `@require` to load the main script.

The interesting part is that the script runs properly when directly used in a bookmarketlet:
`javascript:(function(){BM_MODE=true;var addScript=function(src,onload){var s=document.createElement('script');s.onload=onload;s.src=src;document.body.appendChild(s);};addScript('https://greasyfork.org/scripts/692-manga-loader/code/Manga%20Loader.user.js',addScript.bind(null,'https://greasyfork.org/scripts/12657-manga-loader-nsfw/code/Manga%20Loader%20NSFW.user.js'));})(); `

It also works when it’s merged directly into the main script as this [gist](https://gist.github.com/Taxyovio/9848b8e533d56cbbf6405252389c92fe). 

A safe for work test manga would be https://e-hentai.org/s/5225e47182/2082483-1.

As pointed out by @quoid in this [comment](https://github.com/quoid/userscripts/issues/135#issuecomment-991834178). The `@require` doesn’t account for query parameters and ignores urls not ending with `.js`.

**Comment by quoid** [comment]
This also affects the the installation functionality

**Comment by quoid** [comment]
@Taxyovio this should be fixed in the next build

**Comment by Taxyovio** [comment]
Fixed.
