### ISSUE TITLE
How to use greasyfork

### ISSUE THREAD

**Issue by Jax0rz** [quoid/userscripts#18]
How can I install scripts from greasyfork

**Comment by quoid** [comment]
You'd have to get access to the scripts source code and manually install it with a url checking function like:

```js
function checkPageHost() {
  var w = location.host;
  if (w.indexOf("www.") === 0) {
    w = w.replace("www.","");
  }
  if (w === "google.com") {
    //code to run
  }
}
```

At the current moment there's no support for automatically installing scripts from Greasy Fork or pasting Tampermonkey scripts without editing. This functionality is being considered for future updates.

**Comment by filbo** [comment]
Many userscripts also use GM_xxx() [GM3] or GM.xxx() [GM4] APIs to do their work; I haven't surveyed greasyfork to see what fraction are usable without those, but I imagine it would impact almost any script of substantial size.

GM/TM/VM also pack a lot of semantic information into the header comment (include/exclude sites on which to be injected, etc.)

It would be great to see full GM semantics... (personally I'd rather see GM3, I don't think the GM4 async API has particularly caught on with userscript authors, so userscript runners -- like GM4 itself -- which support only the GM4 API are sort of useless wrt the existing pool of userscripts)

**Comment by quoid** [comment]
I am going to close this thread. 

Implementing GM metadata into *this* extension is beyond scope. I set out to create something simple to facilitate my userscript needs, *until something better came along*. I believe [PageExtender](https://github.com/fphilipe/PageExtender.app) is that *something better.*

Perhaps a project can be spun up in the future to address the lack of "editor" that can easily ingest usersripts in the GM format, but I don't it will be this project - at least not in the near future.
