### ISSUE TITLE
Conflict between GM.xmlHttpRequest and GM_xmlhttpRequest

### ISSUE THREAD

**Issue by v7rzlhb3xg** [quoid/userscripts#182]
_System Information:_
> macOS version: Monterey 12.1
> Userscripts version: 4.0.9 (36)
> Safari version: 15.2

With the latest update, it seems that userscripts that grant both `GM.xmlHttpRequest` and `GM_xmlhttpRequest` for compatibility break the script, see the error in the javascript console below. 

Here's an example script demonstrating the issue.

```
// ==UserScript==
// @name          TestScript
// @description   This is your new file, start writing code
// @match         <all_urls>
// @exclude-match *://*.google.com/*
// @noframes
// @grant        GM.xmlHttpRequest
// @grant        GM_xmlhttpRequest
// @run-at       document-start
// ==/UserScript==
```
<img width="1440" alt="Screen Shot 2021-12-15 at 4 13 58 PM" src="https://user-images.githubusercontent.com/18043024/146265883-0d86c5ce-9f57-4b53-a6e6-2624154b0f04.png">

**Comment by quoid** [comment]
@v7rzlhb3xg thanks for reporting this, I pushed a fix on build 37 which should address this, i really appreciate the bug reports

**Comment by v7rzlhb3xg** [comment]
Seems to be fixed, thanks!

**Comment by quoid** [comment]
@v7rzlhb3xg thank you for reporting it!
