### ISSUE TITLE
Return YouTube Dislike doesn’t work on iOS/iPadOS

### ISSUE THREAD

**Issue by Taxyovio** [quoid/userscripts#194]
I’ve seen [Return YouTube Dislike](https://returnyoutubedislike.com/install) running successfully in the mac as seen in this [video](https://www.youtube.com/watch?v=lKS2ElWQizA). But it doesn’t seem to work on iPad.

**Comment by quoid** [comment]
@Taxyovio thanks for pointing that out

there's a bug in the `GM_addStyle` method. It's broken on the newest version of the desktop extension as well.

If you change

`// @grant        GM_addStyle` (line 22 of the userscript)

to

`// @grant        GM.addStyle`

The issue should be resolved, or at least the issue that was causing the bug on my system:




![IMG_7992E8D08960-1](https://user-images.githubusercontent.com/7660254/148630471-59fac149-e3fc-4712-a623-9c4417f38e3b.jpeg)

**Comment by Taxyovio** [comment]
That worked. Thanks for the quick tip!

**Comment by quoid** [comment]
thanks for reporting it, working on fix!

**Comment by quoid** [comment]
@Taxyovio this should be fixed, if not please let me know
