### ISSUE TITLE
ReferenceError: Can't find variable: browser with GM_addStyle

### ISSUE THREAD

**Issue by sumanth-98-dev** [quoid/userscripts#195]
_System Information:_
> macOS version: 12.1
> Userscripts version: Userscripts Safari Version 4.0.9
> Safari version: Version 15.2 (17612.3.6.1.6)
> Is this issue related to script injection? Yes
> Did the test script (pasted above) successfully run on your machine? Yes

```
GM_addStyle(".TableValue { width: min-content; }");
GM_addStyle(".TableRow { margin-right: 2em; }");
```

These lines are giving `ReferenceError: Can't find variable: browser` error in console. 

<img width="972" alt="Screenshot 2022-01-08 at 11 54 21 AM" src="https://user-images.githubusercontent.com/24863030/148634165-3209511f-f949-4046-941a-8490d563858b.png">

**Comment by sumanth-98-dev** [comment]
As a workaround, I'm using this
https://stackoverflow.com/a/23684230/5524175

**Comment by quoid** [comment]
@sumanth-98-dev this is related to this bug: https://github.com/quoid/userscripts/issues/194

**Comment by quoid** [comment]
For a workaround, you can change `GM_addStyle` to `GM.addStyle` until fix is pushed

**Comment by daniel-white** [comment]
might this be a duplicate too?

**Comment by quoid** [comment]
@daniel-white yes I believe so, since they both use `GM_addStyle`

I fixed this in the latest version which *just* got review by the App Store, you should see the update soon
