### ISSUE TITLE
Popup taking ~6sec for opening 

### ISSUE THREAD

**Issue by sumanth-98-dev** [quoid/userscripts#196]
_System Information:_
> macOS version: 12.1
> Userscripts version: Userscripts Safari Version 4.0.9
> Safari version: Version 15.2 (17612.3.6.1.6)
> Is this issue related to script injection? Yes
> Did the test script (pasted above) successfully run on your machine? Yes

**Comment by sumanth-98-dev** [comment]
Found already existing issue : https://github.com/quoid/userscripts/issues/191

**Comment by quoid** [comment]
@sumanth-98-dev hopefully pushing an update to the app store for this tonight
