### ISSUE TITLE
Filename sanitization not working properly for Chinese characters

### ISSUE THREAD

**Issue by darescloud** [quoid/userscripts#204]
_System Information:_
> macOS or iOS version:ipados15.2
> Userscripts version:1.0.1
> Safari version:newest 
> Is this issue related to script injection?
> Did the test script (pasted above) successfully run on your machine?

the chinese scripts doesn’t work,click install
![1768A321-FEBE-4DA4-9B95-EC850A165950](https://user-images.githubusercontent.com/77814393/148864105-a04fc032-dfdd-4fe2-94eb-ba804d8c693f.png)

**Comment by quoid** [comment]
@darescloud please include link to userscript

**Comment by darescloud** [comment]
https://greasyfork.org/zh-CN/scripts/418804-解锁b站大会员番剧-b站视频解析下载-全网vip视频免费破解去广告-全网音乐直接下载-油管-facebook等国外视频解析下载-网盘搜索引擎破解无限下载等.       please

**Comment by darescloud** [comment]
> @darescloud 请包含用户脚本的链接

https://greasyfork.org/zh-CN/scripts/418804-解锁b站大会员番剧-b站视频解析下载-全网vip视频免费破解去广告-全网音乐直接下载-油管-facebook等国外视频解析下载-网盘搜索引擎破解无限下载等

**Comment by quoid** [comment]
@darescloud 

it's a bug in the filename [sanitization function](https://github.com/quoid/userscripts/blob/116eb4e42d695ef660c0d6aa1ee35e6479b87dec/extension/Userscripts%20Extension/Functions.swift#L15) that does not properly sanitize chinese characters. The filename that gets returned is greater than `255` characters long, [which throws an error](https://github.com/quoid/userscripts/blob/116eb4e42d695ef660c0d6aa1ee35e6479b87dec/extension/Userscripts%20Extension/Functions.swift#L1496)

I will try to fix this weekend. 

If you need a quick fix, you will have to edit the filename and save it to you userscripts folder manually.

**Comment by darescloud** [comment]
> @darescloud 请包含用户脚本的链接



> @darescloud
> 
> it's a bug in the filename [sanitization function](https://github.com/quoid/userscripts/blob/116eb4e42d695ef660c0d6aa1ee35e6479b87dec/extension/Userscripts%20Extension/Functions.swift#L15) that does not properly sanitize chinese characters. The filename that gets returned is greater than `255` characters long, [which throws an error](https://github.com/quoid/userscripts/blob/116eb4e42d695ef660c0d6aa1ee35e6479b87dec/extension/Userscripts%20Extension/Functions.swift#L1496)
> 
> I will try to fix this weekend.
> 
> If you need a quick fix, you will have to edit the filename and save it to you userscripts folder manually.

thank you!but I change the scripts name by hand, it still doesn't work, here is the difference between work and doesn't work
![525F9558-A1A4-43E0-9FAA-7968F0870745](https://user-images.githubusercontent.com/77814393/148868272-9dcd69f5-cfe2-44ff-a266-3643c27c4e38.jpeg)
![179BF71E-C949-442F-BA45-BF9A28205365](https://user-images.githubusercontent.com/77814393/148868279-a31f4a01-a3e4-4a28-9548-10db9d35c9bc.jpeg)

**Comment by quoid** [comment]
@darescloud i don't know the code well enough to tell you why it isn't working, but there seems to be an issue with how the element's css is set, those boxes you link are there. If I comment out lines `488-491` i can see those boxes.

```js
//                     if(!!Position){
// 				left = Position.left;
// 				top = Position.top;
// 			}
```

This is probably due to some difference between this userscript manager and the other you used.

<img width="1247" alt="Screen Shot 2022-01-10 at 10 22 44 PM" src="https://user-images.githubusercontent.com/7660254/148876016-ccce114c-1221-424e-b3d0-1508caadf3c6.png">

**Comment by darescloud** [comment]
> @darescloud i don't know the code well enough to tell you why it isn't working, but there seems to be an issue with how the element's css is set, those boxes you link are there. If I comment out lines `488-491` i can see those boxes.
> 
> ```js
> //                     if(!!Position){
> // 				left = Position.left;
> // 				top = Position.top;
> // 			}
> ```
> 
> This is probably due to some difference between this userscript manager and the other you used.
> 
> <img alt="Screen Shot 2022-01-10 at 10 22 44 PM" width="1247" src="https://user-images.githubusercontent.com/7660254/148876016-ccce114c-1221-424e-b3d0-1508caadf3c6.png">
@quoid 
谢谢解答！thank you！

**Comment by darescloud** [comment]
也许这是一个无法找到要显示的当前位置的错误？当我刷新网络时，它可以显示一段时间。@ quoid

**Comment by quoid** [comment]
@darescloud The author of the script saves the position of the elements to storage with setValue for some reason. 

Then the author tries to read that value but doesn't check if it is undefined before setting the elements position to it. If there was was undefined check I believe the issue would not be present. 

Perhaps there is an issue with how setValue works with this manager compared with how the other manager has implemented that method. I will look more into this issue soon.

**Comment by darescloud** [comment]
@quoid well，i will wait for your updating.

**Comment by quoid** [comment]
This should be fixed in the new release which should be on the App Store shortly
