### ISSUE TITLE
Not working with Return YouTube dislikes

### ISSUE THREAD

**Issue by cr4zypers0n** [quoid/userscripts#206]
// ==UserScript==
// @name         Return YouTube Dislike
// @namespace    https://www.returnyoutubedislike.com/
// @homepage     https://www.returnyoutubedislike.com/
// @version      0.9.0
// @encoding     utf-8
// @description  Return of the YouTube Dislike, Based off https://www.returnyoutubedislike.com/

_System Information:_
> macOS or iOS version: macOS 12.1
> Userscripts version: 4.0.9
> Safari version: 15.2
> Is this issue related to script injection? Yes
> Did the test script (pasted above) successfully run on your machine? Yes

It seems like the 'Return YouTube Dislikes' userscript is not working for me. The extension displays a red (1) symbol and I don't know if that means it's doing it's job or that there is something wrong. Either way, the dislikes count is not appearing.

<img width="294" alt="CleanShot 2022-01-15 at 13 34 00@2x" src="https://user-images.githubusercontent.com/42073454/149622015-baa8bd3d-22f1-4170-a010-9ef0b349e55e.png">
<img width="184" alt="CleanShot 2022-01-15 at 13 34 15@2x" src="https://user-images.githubusercontent.com/42073454/149622016-107add82-ed1d-40d4-961e-0f2cc9863171.png">

Am I doing something wrong or is this script broken?

**Comment by cr4zypers0n** [comment]
Well, that was weird. After creating this issues it started showing up again...

**Comment by quoid** [comment]
> Userscripts version: 4.0.9

You should update to 4.0.10. There's a bug in 4.0.9 that affected that userscript an it was fixed in 4.0.10: https://github.com/quoid/userscripts/issues/195

**Comment by quoid** [comment]
> Am I doing something wrong or is this script broken?

In situations where it appears like the script should be functioning, such as showing up in the popup and seeing the red "number badge" - it's best to open Safari's developer console and see if there are errors logged. A lot of the times it's an issue with the userscript or injected code in those situations.
