### ISSUE TITLE
Show full path on hover

### ISSUE THREAD

**Issue by quoid** [quoid/userscripts#214]
When the user is looking at the save location in the macOS app, if the location is long and truncated the user should be able to see the full path when hovering.

reference: https://github.com/quoid/userscripts/issues/193#issuecomment-1016808977

**Comment by quoid** [comment]
in [v4.1.0, v1.1.0](https://github.com/quoid/userscripts/releases/tag/v4.1.0)

**Comment by sas65-wed** [comment]
مرحبا شكر على كل ما يقدم.. مقدر عملكم مزيد من
ما يفيد

في الأحد، ٢٧ فبراير، ٢٠٢٢ ٠٠:١٥ Justin Wasack ***@***.***>
كتب:
