### ISSUE TITLE
Trailing spaces in metadata cause script to fail to save

### ISSUE THREAD

**Issue by patrickrushton** [quoid/userscripts#218]
I can save an empty script, but after pasting in a user script I get the above error message

**Comment by quoid** [comment]
@patrickrushton 

Can you include the userscript that is giving the error? If you don't want to share the entire script, can you please share the metadata block?

If I can reproduce the issue I should be able to tell you why it is happening.

**Comment by quoid** [comment]
@patrickrushton 

Ok, got it. That error appears when the metatdata is malformed or missing the `@name` key. I will improve the error logging there, thanks for pointing it out.

> There was a trailing space at the end of the first line:

This shouldn't make the script fail to save, so I am going to considering this a bug. I will try to patch this today.

**Comment by quoid** [comment]
I don't think I will release a patch update for this, but the changes will be in the next minor version update

**Comment by quoid** [comment]
done in [v4.1.0, v1.1.0](https://github.com/quoid/userscripts/releases/tag/v4.1.0)

**Comment by sas65-wed** [comment]
البقى معكم مفيد فلنستمر

في الأحد، ٢٧ فبراير، ٢٠٢٢ ٠٠:١٤ Justin Wasack ***@***.***>
كتب:
