### ISSUE TITLE
Script breaking only in Userscripts

### ISSUE THREAD

**Issue by miIktoast** [quoid/userscripts#222]
Script has a download function which works in Tampermonkey but fails in Userscripts.

Script: https://github.com/ccd0/4chan-x

Console:
<img width="763" alt="Screen Shot 2022-01-29 at 06 17 40" src="https://user-images.githubusercontent.com/76277835/151660856-e7cde3e3-00f5-4fc4-aa6d-70006ecc3192.png">

Mac: 12.1
Safari: 15.2
Userscripts: 4.0.11 (43)

**Comment by quoid** [comment]
@miIktoast 

can you included the url you were on when you say this error?

downloaded the script, went to https://boards.4channel.org/w/ and saw a **different** error than you posted, which I believe I just fixed. I saw this error `TypeError: undefined is not an object (evaluating 'name.startsWith')` - something else is posting messages and needed to fix the check on the `GM.xmlHttpRequest` which responds to window messages, this resolved the issue I saw.

If you send me the url you visited when you encountered the issue< i can validate whether this fix also resolves the issue you saw. If so, it will be in the next update.

**Comment by miIktoast** [comment]
It seems adguards extension blocked whatever causes the error you received so I was not seeing it.

I also failed to give steps to recreate my original error:
- open dropdown menu next to image, select download
- select download icon next to filename in post header

**Comment by quoid** [comment]
@miIktoast 

> It seems adguards extension blocked whatever causes the error you received so I was not seeing it.

That sounds right

> I also failed to give steps to recreate my original error:
> - open dropdown menu next to image, select download
> - select download icon next to filename in post header

I've not used this extension before, so I need very explicit directions to recreate the error, such as the url to visit when to do those steps. What is the dropdown? What is the download icon? Please provide images if possible.

Thank you!

**Comment by quoid** [comment]
@miIktoast 

Is this issue that you can not download an image through this icon?
<img width="534" alt="Screen Shot 2022-01-29 at 9 55 10 AM" src="https://user-images.githubusercontent.com/7660254/151665694-298fa9bd-6153-4af7-8b3d-def340349464.png">


If that is the issue it is related to: https://github.com/quoid/userscripts/issues/212 - I have a fix for that on my system and can download the images as expected and will be in the next beta/release - if you want access to it early [you can sign up for beta testing](https://github.com/quoid/userscripts#support)

**Comment by miIktoast** [comment]
Yes that is the issue, thank you! Sorry for not giving detailed steps, morning brain...

**Comment by quoid** [comment]
@miIktoast thanks for reporting it! I found another bug because of this issue so it was very helpful
