### ISSUE TITLE
Adding remote scripts with url containing unicode characters fails

### ISSUE THREAD

**Issue by ghostflyby** [quoid/userscripts#226]
_System Information:_
> macOS or iOS version: macOS Monterey 12.1
> Userscripts version: 4.0.11(43)
> Safari version: 15.2 (17612.3.6.1.6)
> Is this issue related to script injection? No
> Did the test script (pasted above) successfully run on your machine? Yes

Adding remote scripts with url containing unicode characters fails, for example https://greasyfork.org/scripts/416338-redirect-外链跳转/code/redirect%20外链跳转.user.js
> Failed to get remote content

**Comment by quoid** [comment]
Thanks for reporting this @ghostflyby

**Comment by quoid** [comment]
done in [v4.1.0, v1.1.0](https://github.com/quoid/userscripts/releases/tag/v4.1.0)
