### ISSUE TITLE
Page does not finish rendering when executing Alert

### ISSUE THREAD

**Issue by ifuchs** [quoid/userscripts#240]
I am new to Userscripts and I am not sure this is an issue as much as it is a question about how scripts function on ios vs. the Mac. I have a trivial script:
`
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://192.168.3.21/Sys.html
// @icon         https://www.google.com/s2/favicons?sz=64&domain=3.212
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    alert("Hello world!")
})();

`
It does nothing more than show the alert over the page. However, on iOS the alert is shown before the page is rendered fully and on the Mac the page renders beneath the alert. Is there a way to get the script to behave the same on iOS?

**Comment by ifuchs** [comment]
That helped a lot. I would have thought that the default for @run-at of document-end would have been the right setting but I changed it to document-idle and it works as it does on MacOS. Thanks!

**Comment by quoid** [comment]
@ifuchs I'm glad it worked out. I am going to close this issue, if anything else comes up feel free to open another.
