### ISSUE TITLE
Pattern that match the URL is not rigorous, resulting in `@match` may not be correctly matched

### ISSUE THREAD

**Issue by ACTCD** [quoid/userscripts#249]
_System Information:_
> macOS or iOS version: `Unrelated`
> Userscripts version: `v4.1.0, v.1.1.0`
> Safari version: `Unrelated`
> Is this issue related to script injection? `Seemingly`
> Did the test script (pasted above) successfully run on your machine? `Yes`

When I discovered this metadata:
`// @match   *://www.google.com/*`
Can't match the userscript when browser open URL like this:
`https://www.google.com/preferences?prev=https://www.google.com/`

I spent a lot of time to read the source code, and I think I found where the problem.
https://github.com/quoid/userscripts/blob/16a23bd5ea94f9bacbc9a09a21b3ddb779c41d65/extension/Userscripts%20Extension/Functions.swift#L935-L937
I made an online demonstration to show how it matches the web page URL and what kind of problems.
I believe it is obvious:
https://regex101.com/r/xs43bS/1

At first I thought it was a `@match` matching problem, but by looking at the source code, because this occurred in the webpage URL matching stage, I assumed that it should also affect `@include` and other metadata.

**Comment by quoid** [comment]
@ACTCD Thanks for reporting this. This issue I see is in the regex expression not properly separating the various url "parts", does this align with what you are seeing?

Do you have any suggestions for a fix to the expression?

I can work on this soon to, hopefully, properly match against urls that have urls in the `pathname`, unless you have a PR.

**Comment by ACTCD** [comment]
Yes, that's right, because there is no correctly dividing URL parts here, when the subsequent program is tried to match @Match, it's impossible to pass the protocol check, which cannot be correctly matched to the user script.

Sorry, because I‘m not familiar with the Swift language, I cannot give relevant suggestions or PR.

**Comment by quoid** [comment]
@ACTCD 

I've been trying to extract the url components via a regex expression, which functions well most of the time, but as you pointed out, *not always*. I was unaware of the above linked built in foundation structure previously, so I attempted to build my own.

I was just doing some tests here and using the build in structure seems to resolve the issue and I can refactor that `getUrlProps` function to work as follows. It makes life easier and seems to works as intended.

```swift
func getUrlProps2(_ url: String) -> [String: String]? {
    guard
        let parts = URLComponents(string: url),
        let ptcl = parts.scheme,
        let host = parts.host
    else {
        err("failed to parse url in getUrlProps")
        return nil
    }
    return ["protocol": "\(ptcl):", "host": host, "pathname": parts.path, "href": url]
}
```

Here's some test code if you want to try it in a playground like: http://online.swiftplayground.run - if you copy and paste it into a session there, you can see the parsing difference.

```swift
func getUrlProps(_ url: String) -> [String: String]? {
    let pattern = #"^(.*:)\/\/((?:\*\.)?(?:[a-z0-9-:]+\.?)+(?:[a-z0-9]+))(\/.*)?$"#
    let regex = try! NSRegularExpression(pattern: pattern, options: .caseInsensitive)
    guard
        let result = regex.firstMatch(in: url, options: [], range: NSMakeRange(0, url.utf16.count)),
        let ptclRange = Range(result.range(at: 1), in: url),
        let hostRange = Range(result.range(at: 2), in: url)
    else {
        return nil
    }
    let ptcl = String(url[ptclRange])
    let host = String(url[hostRange])
    var path = "/"
    if let pathRange = Range(result.range(at: 3), in: url) {
        path = String(url[pathRange])
    }
    return ["protocol": ptcl, "host": host, "pathname": path, "href": url]
}

func getUrlProps2(_ url: String) -> [String: String]? {
    guard
        let parts = URLComponents(string: url),
        let ptcl = parts.scheme,
        let host = parts.host
    else {
        print("ERROR: failed to parse url in getUrlProps")
        return nil
    }
    return ["protocol": "\(ptcl):", "host": host, "pathname": parts.path, "href": url]
}

var baz = "https://www.google.com/preferences?prev=https://www.google.com/"
//baz = "https://www.google.com/"
if let foo = getUrlProps(baz) {
    print(foo)
}
if let bax = getUrlProps2(baz) {
    print(bax)
}
```

**Comment by ACTCD** [comment]
Using native parsing methods is always the best option, it avoids writing complex and error-prone regular expressions.
Glad you were able to solve this problem quickly and accurately, thanks for the FOSS Safari userscript manager.

**Comment by jrpat** [comment]
The fix for this seems to have broken the ability to match path segments that have domain-like parts in them.

For instance, I used to match cppreference.com search, which looks like `https://duckduckgo.com/?sites=cppreference.com&q=atomic&ia=web` with the rule `@match *://duckduckgo.com/?sites=cppreference.com*`, however that no longer works.

Even if I try using `@match *://duckduckgo.com/*cppreference*`, it still does not match.

`@match *://duckduckgo.com/*` works, but obviously isn't precise enough.

btw, thanks for the great extension!

**Comment by quoid** [comment]
@jrpat

When the page url is compared against the match pattern, the page url's query params are not included - here's [the relevant code](https://github.com/quoid/userscripts/blob/2a83cf0b62932077d0019df5f704c35725f0fa4a/extension/Userscripts%20Extension/Functions.swift#L1049) - this was always intended but previously the regex pattern wasn't properly dropping the params, [that code is here](https://github.com/quoid/userscripts/blob/e7b5fc72c44405034409efbe41ca4dd9d9e0b01e/extension/Userscripts%20Extension/Functions.swift#L1049).

I would use `@include` instead of `@match` to match against query params, since that uses the `href` rather the a deconstructed url. 

example that seems to work:

```js
// ==UserScript==
// @name        NewScript-tm4ycsfo
// @description This is your new file, start writing code
// @include       *://duckduckgo.com/*cppreference*
// ==/UserScript==

console.log("worked");
```

**Comment by ACTCD** [comment]
@jrpat @quoid
Since it is recommended to use @match instead of @include, because the `@match` is safer and stricter, a more feasible approach to exact matching is to judge further in the script.

```
// ==UserScript==
// @match *://duckduckgo.com/*
// ==/UserScript==

if(new URL(location).searchParams.get('sites') == 'cppreference.com') {
    // Do what you need...
    console.log("worked");
}
```

**Comment by quoid** [comment]
@ACTCD 

Great suggestion!

**Comment by jrpat** [comment]
@ACTCD makes sense - thanks very much!
