### ISSUE TITLE
Request to add hidden script number option.

### ISSUE THREAD

**Issue by zhuozhiyongde** [quoid/userscripts#250]
This is a feature request.
I would like the macOS version of the app to offer an option to hide the little red dot (which shows the number of scripts in effect on this page). Because in all my Safari extensions, only Userscript appears in colors other than the non-thematic color, which makes me feel very uncomfortable.
Thanks for your consideration.

**Comment by quoid** [comment]
@zhuozhiyongde you can already do this :)

https://github.com/quoid/userscripts#settings-modal

The option is `Show Toolbar Count`

**Comment by zhuozhiyongde** [comment]
> @zhuozhiyongde you can already do this :)
> 
> https://github.com/quoid/userscripts#settings-modal
> 
> The option is `Show Toolbar Count`

Thanks, I didn't look carefully before and didn't see this option, sorry.
