### ISSUE TITLE
Why can't userscripts detect this script and install it?

### ISSUE THREAD

**Issue by JOJOforshaun** [quoid/userscripts#261]
_System Information:_
> macOS or iOS version:iOS 15.5
> Userscripts version:1.2(24)
> Safari version:15
> Is this issue related to script injection?
> Did the test script (pasted above) successfully run on your machine?

https://raw.githubusercontent.com/91p2022/91/main/91porn-vip.js

![B3AB2809-2376-4A44-A89A-24142040E623](https://user-images.githubusercontent.com/63553362/169940162-8c08e558-f57a-4fdc-8f9f-c03b6e2ae2b5.png)

**Comment by quoid** [comment]
Because the url doesn't end with `user.js`
