### ISSUE TITLE
Changes to `@grant` and `@inject-into`

### ISSUE THREAD

**Issue by quoid** [quoid/userscripts#265]
The next patch update will change a few things, that while programmatically minor (from a development standpoint), that can change the way your userscripts work. Since I don't have discussions enabled on this repo, this issue is more of a public announcement, but comments and discussion are more than welcome. Here are the changes:

- `content` is the new default value for the `@inject-into` metadata key (i.e. if you don't include `@inject-into` the value, `content`, will be assumed)
- when `@grant` has **any** value, `@inject-into` values of `page` and `@inject-into` values of `auto` will **automatically** be reverted to `@inject-into content` (a message will be printed to the browser console when this occurs)
- users **can still** inject into the `page` context, however they can **not** use `GM` apis in the `page` context

The reason these changes are being implemented is to ensure the the `page` context can  not gain access to the privileged `GM` apis.

Related issue discussion: #252

**Comment by ACTCD** [comment]
Just as a hint, if this change causes your script to not work, for most scripts that used to work fine in `quoid/userscripts`, you may just need to explicitly declare `@inject-into page` in the script after to resume work.

For some other cases, you may be using both GM APIs and page scripts, please try to separate your script logic, manually add page scripts to the page DOM, and keep the whole script in the content script context to keep everything working.

For the remaining cases, you can describe your use case and maybe we can tell you the right way to implement it. Always remember that `unsafeWindow` is unsafe, properly designed user scripts do not need and should not use it, and it may not be implemented correctly in Safari at this time, so it is currently not supported.

**Comment by KamilTheDev** [comment]
Please add an option to "enable unsafe mode", so that Userscripts will work as they did in the prior version.

After updating to v1.2.1, most of my userscripts are not working.

I would happily downgrade back to v1.2.0, but unfortunately iOS doesn't let you.

**Comment by quoid** [comment]
@KamilTheDev 

Can you give me an example of a userscript that worked prior but doesn't work any more? Preferably something simple?

**Comment by quoid** [comment]
The main goal of this change was to isolate the `GM` apis from the page context and that's what was done. You don't want the page to be able to execute those methods.

If a developer wants the expose those methods to the page context, I can't stop them from doing so, but that functionality is no longer built into the extension to do so. A motivated developer can still expose those function to the page, but the effort required to do so might be better spent elsewhere.

If anyone has any suggestions on how to improve the functionality to securely give the page access to the methods (if that even exists) or how to pull the page context into the context of the content script, **please do share**.

**Comment by quoid** [comment]
Another note:

I reverted the default `@inject-into` value to `auto` which tries to inject in the `page` scope. Now that the `GM` apis are properly isolated, I think should be OK and this [matches ViolentMonkey's default behaviour](https://violentmonkey.github.io/api/metadata-block/#inject-into)

**Comment by KamilTheDev** [comment]
> I reverted the default `@inject-into` value to `auto` which tries to inject in the `page` scope first.

Thanks, that was the cause of the problems. Also, `@grant none` causes `@inject-into page` to be disallowed, that needs to be fixed.

With these changes, will something like a Popup Blocker userscript be able to work? It overrides `window.open`, uses `GM_*Value` for storing values, appends HTML to page, etc.

Example userscript: https://github.com/Eskander/ultra-popup-blocker/blob/main/src/ultra-popup-blocker.user.js

Well, I'm not sure if that userscript would work either way, if synchronous `GM` functions aren't supported.

**Comment by scholtzm** [comment]
Is there a way to have access to GM API but also to page's context?

**Comment by scholtzm** [comment]
@ACTCD I use GM_xmlhttpRequest to load cross-origin resources but I also use some globals used by the website available in the page context.

**Comment by scholtzm** [comment]
@quoid @ACTCD Perhaps there could be a way to preserve `@inject-into page` even if there are some grants for GM API? 

This way I could have a single script for both Tampermonkey and Userscripts users. Right now, all @grants are honoured and @inject-into is not, but I would like to achieve the exact opposite -- honour @inject-into and disregard @grants.

**Comment by scholtzm** [comment]
> Userscripts behaves in the same way as Tampermonkey.

It certainly does not otherwise the same script that works in Tampermonkey would also work in Userscripts.

**Comment by quoid** [comment]
@scholtzm 

I understand your frustration, I feel it to. As mentioned by @ACTCD, and as I am sure you know by now, the lack of `unsafeWindow` in Safari does limit some of our possibilities when writing safe userscripts using GM apis. There could still be way to accomplish this, but I unsure how to implement it and I've tried a bunch of different things.

The changes that were made recently didn't prevent users from injecting into the page scope with GM apis, really. We just made it so that functionality wasn't built into a metadata field. We **can't** control what users do with their code and it's still possible, albeit more difficult. (example listed below)

> Then I would need to distribute 2 different scripts.

Could you send me a userscript, or a simplified example of one, where you are dealing with this? There might be a way to check if the window object you are looking for is available and if not, use an alternate implementation, but I understand that is a lot of work to support one userscript manager.

Also, don't forget that when injecting into the page scope, the userscript has to follow the page CSP. If the page has a strict CSP, the userscript will not be executed. Tampermonkey gets around this by manipulating page headers (i believe), but no such API exists for Safari (yet).

An alternative to what is pasted below would be having something like `@inject-into unsafePage` which ignores restrictions. However I am torn on that because of how *unsafe* doing that is. I wonder if all consumers of userscripts really understand that risk.

---

Example injecting into the page scope with a GM API - I did this very quick, so there could be an easier way to accomplish it. I am logging the `browser` global as that is a good way to know what scope you are in. The `page` scope only has `browser.runtime`, while the content script scope has more.


```js
// ==UserScript==
// @name        page scope GM api
// @description This is your new file, start writing code
// @match       *://*/*
// @grant        GM.xmlHttpRequest
// ==/UserScript==

function baz() {
GM.xmlHttpRequest({
    binary: true,
    method: "GET",
    url: "http://static.reddit.com/reddit.com.header.png",
    responseType: "blob",
    onload: function(response) {
        console.log("onload");
        console.log(response);
        console.log(response.response);
    }
});
}
const code = `
    console.log(browser);
    const US_uid = "${US_uid}";
    const GM = {};
    GM.xmlHttpRequest = ${GM.xmlHttpRequest};\n
    ${baz}baz();
`;
const tag = document.createElement("script");
tag.textContent = code;
document.head.appendChild(tag);
```

**Comment by scholtzm** [comment]
Thank you @quoid for a thorough explanation.

Your example game me another idea, how about calling `page` globals from userscript that is using `@inject-into content` via the script tag injection?

**Example:**
(The page I tested this on uses jQuery and has `$` in global scope.)

```js
// ==UserScript==
// @name        Test - call page from content scope
// @description This is your new file, start writing code
// @match       *://*/*
// @inject-into content
// ==/UserScript==

console.log('from content', typeof $);

const code = `
  console.log('from page', typeof $, $.toString());
`;

const tag = document.createElement("script");
tag.textContent = code;
document.head.appendChild(tag);
tag.remove();
```
<img width="406" alt="image" src="https://user-images.githubusercontent.com/2640934/184410691-baaecdf3-94f2-408c-8a8a-757ad6dd0b0d.png">

Is this an OK approach to take? I might be missing some crucial detail why this is not a good idea or won't work properly.

**Comment by quoid** [comment]
@scholtzm 

Your example looks similar to what I did, I don't see any difference. You could update the page globals through a script tag (if needed) and it would be **better** than my example because you don't expose the `GM` api to the page scope. Although, my example was just trying to show *how* you could get a `GM` api into the page scope.

> I might be missing some crucial detail why this is not a good idea or won't work properly.

You can still face an issue with the page [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). If the page has a strict CSP, then whatever you inject through a script tag won't get executed. There **are** ways to avoid page CSP issues, one of which I believe TamperMonkey uses which is header manipulation, but as mentioned above that's not possible with Safari. Another way is by using [`web_accessible_resources`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/web_accessible_resources) but attempting to bake that into this extension would incredibly difficult if not, impossible.

At a higher level, the main reason we avoid `GM` apis in the page scope is because that could allow page javascript to gain access to the privileged APIs and to the background/content script scope of the extension. Any nefarious code running on a page could do a lot of bad things if it had that kind of access.

**Comment by scholtzm** [comment]
@quoid I took a stab implementing it in the script but I'm not sure I can make it work. Sometimes I need to retrieve value from `page` context and in one case I actually pass my own callback function as an argument.

Makes me wonder again about `unsafePage`. It would solve a lot of issues for scripts that require this functionality. I don't see much difference between using `unsafePage` and exposing GM API as shown in your example other than shifting the responsibility from script to meta. Though the final decision is up to you of course.

**Comment by quoid** [comment]
> I don't see much difference between using unsafePage and exposing GM API as shown in your example other than shifting the responsibility from script to meta.

I think that's the important distinction. I am not sure I am comfortable giving userscript authors an easy to way to create insecure userscripts. Obviously they can do it if they really want to, but I don't want to "advocate" for that. [The warning on this page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts) is good to remember:
<img width="784" alt="Screen Shot 2022-08-12 at 3 22 44 PM" src="https://user-images.githubusercontent.com/7660254/184429136-d982a80c-5416-4161-9cea-92c23738ac11.png">

However, it is worth considering an explicit *unsafe* directive if others feel these security concerns are overblown.

**Comment by scholtzm** [comment]
Yeah, I fully understand what you're saying and I don't think your concerns are overblown as an author of this project.

I have one more alternative to consider regarding `@inject-into` in combination with `@grant`:

- if `@inject-into` is not set, then `@inject-into` is set to `auto`
- if `@inject-into` is `auto`
  - if `@grant`s are requested, then `@inject-into` is `content` 
  - if `@grant` is `none`, then `@inject-into` is `page`
- if `@inject-into` is `content`, all `@grant`s are provided
- if `@inject-into` is `page`, no `@grant`s are provided (+ warning in the console)

Essentially, this would allow me to define this meta[1] and provide special error for Userscripts (mostly iOS) users that this specific feature is not available for them. This would cover the case I described in one of my comments above:

> This way I could have a single script for both Tampermonkey and Userscripts users. Right now, all `@grant`s are honoured and `@inject-into` is not, but I would like to achieve the exact opposite -- honour `@inject-into` and disregard `@grant`s.

[1]
```
@inject-into page
@grant       GM_xmlhttpRequest
```

**Comment by quoid** [comment]
> I have one more alternative to consider regarding @inject-into in combination with `@grant`

That combination you describe is how it should be functioning now. Is it not?

Another thing that might help is to detect if the user is on iOS or Safari with javascript. That way you can deliver a different experience for those users. Below is a small example but there are other `window` objects you could check for.

```js
if (window.ApplePayError && !window.DeviceMotionEvent) // Safari Desktop
if (window.ApplePayError && window.DeviceMotionEvent) // iOS Safari
```

**Comment by scholtzm** [comment]
> That combination you describe is how it should be functioning now. Is it not?

If I set any `@grant`, then `@inject-into` is automatically set to `content`.

**Comment by quoid** [comment]
@scholtzm I understand now - under these circumstances don't change the `inject-into`, simply omit adding the `grant` APIs.

Quickly thinking about this, I don't see any issue with that. Rather than warning the user that the `inject-into` was changes, could simply warn the user that `grant`s were omitted due to the `inject-into` value.

This change could take time to get into a release build, in the meantime you could do the following:

`if (window.browser.extension && window.ApplePayError) // user on safari, **outside** of page scope`

**Comment by quoid** [comment]
@scholtzm 

I am pushing a beta build that includes the above changes, if you're not on beta you can sign up from links on the bottom of the `README` or shoot me an email (on my profile page)

**Comment by scholtzm** [comment]
Yep, this is what I meant with my comments. Will check out the BETA build.

**Comment by scholtzm** [comment]
Tested both macOS and iOS Betas and can confirm it works as expected for my use case. 👍

**Comment by quoid** [comment]
@scholtzm after a week or so I will push to app store

**Comment by scholtzm** [comment]
> @scholtzm after a week or so I will push to app store

Is there any chance the release will happen in the upcoming week?

**Comment by quoid** [comment]
@scholtzm I can submit it to today. It usually takes a day or so to get pushed as an update to users.

**Comment by quoid** [comment]
closing this again, the latest build contains the newest changes

**Comment by quoid** [comment]
@ACTCD 

> You still use window.postMessage in the content script context to pass the GM APIs call, then the page script only needs to listen to the Message event to obtain the current US_uid, and then easily call the GM APIs this should only be @grant in content scripts.


The content script scope is isolated from the page scope, they have different `window` object. Are you saying that even those the `window` object is a completely different in the content script scope, somehow the page `window` can still listen to message events there?

> Since GM APIs are only allowed in content scripts, you should stop using window.postMessage to pass calls, you should directly use browser.runtime.sendMessage to pass calls, and handle the return results.

Yes, that should still be done.

**Comment by quoid** [comment]
@ACTCD 

> Yes, I wrote a simple script to test, the page script can completely listen to the message sent in the content script.

Could you send me that script? My email is on my profile page or you could post it here

**Comment by quoid** [comment]
@ACTCD 

The update readme text will be:

> Userscripts currently supports the following api methods. All methods are asynchronous unless otherwise noted. Users must `@grant` these methods in order to use them in a userscript. When using API methods, it's only possible to inject into the content script scope due to security concerns.

**Comment by quoid** [comment]
> the page script can get the US_uid by listening to the message whenever it is called, and then it can directly constructs the same window.postMessage message to call privileged APIs.

I should have elaborated to say, *arbitrarily execute API methods*. What you mention above, although unlikely, is a possibility and #315 should resolve it.

**Comment by quoid** [comment]
@ACTCD 

I understand what you are saying and agree. What I was alluding to was that if the content script does not contain an API method, the page script shouldn't be able to call it. Example: the content script only contains the `closeTab` method, the page script can call it, but the page script can't call `setValue` since the content script doesn't have that method granted.

Previously when the methods were in the content script itself, the page script could arbitrarily call any method at any time.

**Comment by MotherOfClamperl** [comment]
> @quoid   
> ```js
> // ==UserScript==
> // @name        page scope GM api
> // @description This is your new file, start writing code
> // @match       *://*/*
> // @grant        GM.xmlHttpRequest
> // ==/UserScript==
> 
> function baz() {
> GM.xmlHttpRequest({
>     binary: true,
>     method: "GET",
>     url: "http://static.reddit.com/reddit.com.header.png",
>     responseType: "blob",
>     onload: function(response) {
>         console.log("onload");
>         console.log(response);
>         console.log(response.response);
>     }
> });
> }
> const code = `
>     console.log(browser);
>     const US_uid = "${US_uid}";
>     const GM = {};
>     GM.xmlHttpRequest = ${GM.xmlHttpRequest};\n
>     ${baz}baz();
> `;
> const tag = document.createElement("script");
> tag.textContent = code;
> document.head.appendChild(tag);
> ```
This snippet only works for xmlHttpRequest, the others I'd like to use (setValue, getValue, deleteValue) don't work because the stringified function say ```function() {[Native code]}```. How can I do the same for them?

**Comment by quoid** [comment]
@MotherOfClamperl that's a fairly old snippet and I don't believe it should work in more recent versions.

**Comment by MotherOfClamperl** [comment]
@quoid yeah only just tested it on a "page" script and got this error: ```TypeError: undefined is not an object (evaluating 'browser.runtime.onConnect.addListener')```

...so there's no ways left to expose xmlhttpRequest at the very least? 

I'd like to have userscripts that have persistent data/settings without needing any additional content scripts in addition to the page script. 

I could just use http://localhost + fetch rest API, but the userscripts are synced to my phone, and it would suck having 0 settings in some userscripts without additional content scripts. Only way around this I could think of is running an additional server on iOS using localhost (since connecting via network (eg: http://192.168.x.x) triggers CORS with fetch, as well). But I don't think that's possible...?

**Comment by umangkumarr** [comment]
<img width="462" alt="Screenshot 2023-07-24 at 09 14 59" src="https://github.com/quoid/userscripts/assets/76395302/0eaec0c3-5511-4c72-b255-27c7ae7c0372">
<img width="1089" alt="Screenshot 2023-07-24 at 09 16 01" src="https://github.com/quoid/userscripts/assets/76395302/9d8cbf7b-106d-4c46-a091-65fea5967c30">

If someone could help me with this.

Link to userscript: https://greasyfork.org/scripts/38050-cf-predictor/code/CF-Predictor.user.js

System Information:
> macOS : Version 13.4.1 (c)
> Userscripts Safari Version 4.4.2 (73)
