### ISSUE TITLE
CSS types not injecting into iframes

### ISSUE THREAD

**Issue by quoid** [quoid/userscripts#268]
CSS type userscripts are not injecting into sub-frames. When a parent frame has a sub frame that requests a css file, the css is injected into the parent frame, not the requesting sub frame.

Should check for [`frameId`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/insertCSS) on the `API_ADD_STYLE_SYNC` request.

related: #151

**Comment by lslqtz** [comment]
Now I know that Safari may not support `frameId`.

If that's right, would this parameter `allFrames` help alleviate the problem? But the question is whether Safari does not support this parameter either. The problem I can imagine is that it will cause two functions (`@match` and `@include`) to fail for the iframe. 

Anyway, thanks for the discovery, hope Safari will support these sooner.

**Comment by quoid** [comment]
> If that's right, would this parameter `allFrames` help alleviate the problem? 

Possibly, I will test that when trying to solve this issue. Thanks for the suggestion.

**Comment by quoid** [comment]
@lslqtz 

I changed the way css injected in the above commit. Instead of using [`tabs.insertCSS`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/insertCSS), a `style` element is created and added to the `head` of the document (similar to how css injection happened prior to the update).

It seems that `allFrames` would not be a good solution, so I had to come up with something else. I doubt Safari will ever support `cssOrigin` or `frameId` for `insertCSS`, but I did see [`scripting.insertCSS`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/insertCSS) has support for it's equivalent [`frameId`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/InjectionTarget) value, which is the `target` object. However, it still lacks support for `origin` and I am not ready to make the move to manifest V3.

Note: that the execution of the Javascript that create the `style` element in the `document` happens in the isolated content script scope, so it shouldn't be blocked by content security policies.

**Comment by ACTCD** [comment]
It seems that `UserCSS` is the same as `UserScript`, in addition to the `CSP` problem, there is also the problem of injection timing. When `UserCSS` cannot be injection in stabilized and early enough timing, users will face unpleasant rendering flickering problems, and when `UserScript` cannot be injection in stabilized and early enough timing, cannot prevent some aggressive behaviors of page scripts.

It seems that currently solving these problems can only be achieved by some `Mitm` tools, it is not the best layer to solve the browsing experience, but it seems to be the only way to ensure these problems are solved in stable and early enough, and without being affected by browsing limits and constraints of the extension API. I still hope users to be able to personalize and optimize their browsing experience by solving most problems in simply scripting environment at the browser level.

**Comment by quoid** [comment]
I am both unsurprised and shocked that such integral parts of the API are still lacking.
