### ISSUE TITLE
Allow discussions here to share our scripts and discuss non-issues?

### ISSUE THREAD

**Issue by waynebloss** [quoid/userscripts#270]
Hello. Thanks for this free software! I'm wondering if you would enable the Discussions feature in this repo, so we don't fill up your Issues with non-issues?

Also, just wanted to share one of my favorite scripts. I took this file which was built for a Chrome extension and it works beautifully in Userscripts-iOS. It removes all Google tracking links from results, so you can actually copy URLs and navigate to results faster - https://github.com/Rob--W/dont-track-me-google/blob/master/contentscript.js

I also changed line 162 to do this: `return decodeURIComponent(url[1]).replace("www.reddit.com", "old.reddit.com");`

If any other sites link to reddit, I have another script called "old-reddit" that targets `www.reddit.com` but it's slower than modifying the Google results because it has to wait to run... That script was borrowed from Greasyfork and modified to call `window.stop()` before replacing the location - https://greasyfork.org/en/scripts/44669-bring-back-old-reddit/code

**Comment by quoid** [comment]
Sorry I missed this issue @waynebloss 

That's a good idea, I enabled [discussions on this repo](https://github.com/quoid/userscripts/discussions). Feel free to post about non-issues or questions there.

Thanks for sharing your userscripts. For redirects, I am personally utilizing the new `declarativeNetRequest` feature that was recently implemented. It's a bit quicker than relying on plain userscripts and you can do a lot more than just redirects. You can read about the API [here](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/). 

In the example below I am passing a single object in the userscript body, but you can pass an array of objects for multiple rules in a single "userscript". I should probably post this in the new discussions area.

```js
// ==UserScript==
// @name        Reddit Redirect
// @description Redirects all Reddit requests to the old version of the website
// @run-at request
// ==/UserScript==

{
    "id": 6,
    "priority": 1,
    "action": {
        "type": "redirect",
        "redirect": {
            "transform": { "scheme": "https", "host": "old.reddit.com" }
        }
    },
    "condition": { "urlFilter": "||www.reddit.com", "resourceTypes": ["main_frame"] }
}
```

**Comment by waynebloss** [comment]
Thanks, I’ll try it out!
