### ISSUE TITLE
Script no longer injecting

### ISSUE THREAD

**Issue by BlackAsLight** [quoid/userscripts#273]
One of my scripts no longer injects on some of its match statements. All the ones it has ends in an asterisk *, but the ones where it's an asterisk in a query seem to fail. Nothing in my scripts has changed, but for some reason now it's no longer being injected. I know it's not being injected as it doesn't show up on the extensions page thing. 

Isn't matching: `https://politicsandwar.com/index.php?id=90*`

Is matching: `https://politicsandwar.com/nation/trade/*`

I've only tested it on iPhone and iPad and both seem to have this bug.

**Comment by quoid** [comment]
There was a bug in the prior implementation of the matching function that was erroneously matching against url query strings.

If you want to match against query params, use `@include` or some other functionality within the userscript.

See: 
- https://github.com/quoid/userscripts/issues/249
- https://stackoverflow.com/a/20463282/3126477

**Comment by BlackAsLight** [comment]
It does seem to be matching with the include after a quick test, although I do want to note that in tampermonkey, both match and include work with the above example. Tampermonkey also likes to give a warning about using `@include`. Either way I'd consider this issue closed.

**Comment by quoid** [comment]
Glad it worked out.

>  I do want to note that in tampermonkey, both match and include work with the above example. 

Out of curiosity, which one is matching? `https://politicsandwar.com/index.php?id=90*` or `https://politicsandwar.com/nation/trade/*`

For the first one, that has a query param in the url, which wouldn't get passed to the [matching function](https://github.com/quoid/userscripts/blob/2a83cf0b62932077d0019df5f704c35725f0fa4a/extension/Userscripts%20Extension/Functions.swift#L1071) so a match won't ever occur. To be a bit a more clear, when matching the [page url is deconstructed](https://github.com/quoid/userscripts/blob/2a83cf0b62932077d0019df5f704c35725f0fa4a/extension/Userscripts%20Extension/Functions.swift#L1049), and the url params aren't "sent over" to the matching function. So if the match pattern is `https://politicsandwar.com/index.php?id=90*` and the page url is `https://politicsandwar.com/index.php?id=900abc`, the actual **path** regex will be something like `^\/index\.php\?id=90.*$`, but the path that gets passed is `/index.php`.

I tried to emulate how google handles (handled?) [matching](https://developer.chrome.com/docs/extensions/mv3/match_patterns/) which seemed to disregard url params. I am not totally sure why.

**Comment by ACTCD** [comment]
@quoid  According to [its documentation](https://www.tampermonkey.net/documentation.php?ext=dhdg#_match), it's not a match implemented strictly according to the standard.

In fact I specifically tested this a while ago, each extension's implementation is not exactly the same, and eventually I decided that as a cross-extension user script, I couldn't rely on this metadata for an exact match, so I wrote the required judgment in inside the script.
