### ISSUE TITLE
Something went wrong: click to retry.

### ISSUE THREAD

**Issue by ACTCD** [quoid/userscripts#277]
![Something went wrong](https://user-images.githubusercontent.com/101378590/176061887-19b2b0ae-f818-467c-9aec-2c52ad8b17be.jpg)

Under any website, I can't open the extension interface, it keeps showing the above image error, even click to retry.

This issue only occurs on one specific device, even reinstalling the app doesn't fix it, But the same actions and scripts work fine on other devices.

This problem occurs after installing a specific script [ACT.Google.DM.NCR.user.js](https://github.com/ACTCD/Userscripts/blob/main/userjs/ACT.Google.DM.NCR.user.js), if I remove this script the problem is solved, But as described above this script works fine on other devices.

The following is the log information collected when the error occurs:

Console.app:
```
Userscripts-iOS Extension (CoreFoundation)
Couldn't read values in CFPrefsPlistSource<0x10321fb00> (Domain: group.com.userscripts.ios, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
```
popup console:
```
[Log] Error for init promise: Error: Error calling runtime.sendNativeMessage(): Error Domain=SFErrorDomain Code=3 "(null)". (popup.js, line 4167)
```

**Comment by quoid** [comment]
I saw this when the extension was being terminated by Safari due to hitting the memory limit. This thread has more info: https://github.com/quoid/userscripts/issues/135#issuecomment-944925874

Do you see any generic memory limit messages in the log? It would look like this: https://github.com/quoid/userscripts/issues/135#issuecomment-945169799

**Comment by ACTCD** [comment]
@quoid Yes, I found the exact same `mem limit` log message.

I saw the link mentioned that this problem existed before iOS15.1, I checked the system version of this device and it is indeed a device with iOS15.0, so I assume that upgrading the system should solve it.

Looks like a duplicate issue, I will close it.
