### ISSUE TITLE
If the xx.user.js page has injected dom, userscripts extension won't show the 'Usersciprt Detected' message

### ISSUE THREAD

**Issue by maggch97** [quoid/userscripts#295]
![035ED8F7B55D951DA46AE4B5272473DC](https://user-images.githubusercontent.com/23057110/181505756-d9472892-8d30-4135-b6ad-654c792ed733.png)

**Comment by quoid** [comment]
@maggch97 

Could you provide the page url?

**Comment by maggch97** [comment]
> @maggch97
> 
> Could you provide the page url?

https://2gether.video/release/extension.user.js . If I install this script and reopen this script. The userscripts won't show 'Usersciprt Detected'
