### ISSUE TITLE
URLs to local network machine + port number

### ISSUE THREAD

**Issue by robinwit** [quoid/userscripts#301]
_System Information:_
> macOS  version: 12.5 (21G72)
> Userscripts version: 4.2.2
> Safari version: 15.6 (17613.3.9.1.5)
> Is this issue related to script injection? I think so
> Did the test script (pasted above) successfully run on your machine? Yes

Injection doesn't seem to work for url's pointing to a machine on the local network, could be related to the port number as well.
This is the output from the script:
> This is a test script - http://syno:8112/

My user stylesheet:
```
/* ==UserStyle==
@name        Deluge
@description 
@match       http://syno:8112/*
==/UserStyle== */
@import "https://theme-park.dev/css/base/deluge/organizr.css";
```

Combinations I tried for `@match`:
- http://syno:8112
- http://syno:8112/
- http://syno:8112/*
- http://syno.local:8112
- http://syno.local:8112/
- http://syno.local:8112/*

The only thing that works is `<all_urls>` .

**Comment by quoid** [comment]
@robinwit ports are ignored with match patterns, meaning you get access to all ports

`http://syno.local/*` should work

if it doesn't let me know and alternatively you could use a regex pattern with `@include`

**Comment by robinwit** [comment]
`@include` works with `http://syno:8112/*`, thanks! Could have found that, thanks for taking the time to reply.
`@match` didn't work with either of these:
- http://syno/*
- http://syno.local/*

**Comment by quoid** [comment]
@robinwit 

What was the url of the page you were trying to match to?

Ports should simply be ignored with `@match`. The url props for `http://syno.local:8112/foo` would be:

```
["href": "http://syno.local:8112/foo", "pathname": "/foo", "protocol": "http:", "host": "syno.local"]
```

which should match against the following pattern: `http://syno.local/*`

**Comment by robinwit** [comment]
Oh… It gets more interesting… :D

`@match http://syno.local/*` works when visiting `http://syno.local:8112` (I must have visited the url without `.local` before)
`@match http://syno/*` does not work when visiting `http://syno:8112` 

But actually, I have other services running on other ports, so I really need to be able to include the port.

**Comment by quoid** [comment]
> `@match http://syno/*` does not work when visiting `http://syno:8112`

In the current implementation, you can only omit the `.tld` if you are using a singular wildcard `*`. Examples of valid match patterns:

- `*`
- `https://*.google.com/*`
- `*://*.net/*`
- `https://example.org/foo/bar.html`

Something like `http://syno/*` would be seen as an invalid pattern with the current implementation. I believe the change would be marginal to allow for patterns like that or, say, `*://localhost/*` - **however ports will always be ignored with `@match`**.

You can see the regex for the match parts here: [`^(http:|https:|\*:)\/\/((?:\*\.)?(?:[a-z0-9-]+\.)+(?:[a-z0-9]+)|\*\.[a-z]+|\*)(\/[^\s]*)$`](https://github.com/quoid/userscripts/blob/71094303ef8b10cd7861ccb1166c678d6b81ebf3/extension/Userscripts%20Extension/Functions.swift#L1097)

Changing that to the follow, *should* allow for hosts without `.tld`: `^(http:|https:|\*:)\/\/((?:\*\.)?(?:[a-z0-9-]+\.)+(?:[a-z0-9]+)|\*\.[a-z]+|\*|[a-z0-9]+)(\/[^\s]*)$` - this would give us the following host patterns:


- `(?:\*\.)?(?:[a-z0-9-]+\.)+(?:[a-z0-9]+)` - `https://www.example.foo/page`
- `\*\.[a-z]+` - `https://*.example.foo/page`
- `\*` - `https://*/page`
- `[a-z0-9]+` - `https://example/*` (not currently implemented)

**[We probably should allow hosts without `.tld`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns)**

**Comment by quoid** [comment]
updates in beta build ^
