### ISSUE TITLE
GM_info.script.icon should return a string, not string[]

### ISSUE THREAD

**Issue by scholtzm** [quoid/userscripts#302]
_System Information:_
> macOS or iOS version: Both
> Userscripts version: Latest
> Safari version: Latest
> Is this issue related to script injection? Not really
> Did the test script (pasted above) successfully run on your machine? Yes

This is more of a feature request to improve feature parity with other script managers (such as TM or VM).

`@icon` property can be used in Metadata Block but cannot be accessed via `GM_info.script.icon`.
From my understanding, it is currently not possible to access this value (other than perhaps parsing `scriptMetaStr`). [1][2]

For reference, I opened identical report in VM repo ~2 years ago: https://github.com/violentmonkey/violentmonkey/issues/1031

[1] https://github.com/quoid/userscripts/blob/71094303ef8b10cd7861ccb1166c678d6b81ebf3/extension/Userscripts%20Extension/Functions.swift#L1302-L1318
[2] https://github.com/quoid/userscripts#api

**Comment by quoid** [comment]
@scholtzm 

Currently it should be possible to access this by `GM.info.script.icon` if included in the metadata. However, it returns and array of strings (`Array<string>`), rather than a `string`.

Are you saying it should return a `string`?

**Comment by scholtzm** [comment]
@quoid 

You are right, it works. But it's not mentioned in the README: https://github.com/quoid/userscripts#api
Should it be added?

I tested this in TM AND VM and it returns `string`, not `string[]`.

Also, I tested following script:

```js
// ==UserScript==
// @name        Icon Test
// @description This is your new file, start writing code
// @match       *://*/*
// @icon https://www.example.com/icon.png
// @icon https://www.example.com/icon2.png
// ==/UserScript==

console.log(GM.info.script.icon);
console.log(GM_info.script.icon);
```

In both TM and VM, it only returns the first icon as `string` (second `@icon` seems to be ignored) and US returns `string[]` with both icons.

**Comment by quoid** [comment]
>  But it's not mentioned in the README: https://github.com/quoid/userscripts#api ... Should it be added?

`@icon` does nothing in this userscript manager so I omitted it from the readme. I believe in other userscript managers it shows that icon somewhere.

I don't know if it should be added since it doesn't do anything here, it's also shown as "unsupported" in the built in editor linter (image below)

> I tested the script above in TM and VM and it returns string, not string[].

We can change it to `string`, but again it does nothing. I am not against changing it, but do you think it is worth it? I don't have a use case in mind.

**Comment by scholtzm** [comment]
I'd say the use cases for accessing `@icon` are certainly limited but they do exist.

In my case, I display the `@icon` inside a small "script info" panel which also displays some other info such as `@version` and also includes a link to script homepage.

**Comment by quoid** [comment]
@scholtzm ok ill add support for it, will be in next beta build

**Comment by scholtzm** [comment]
I did some brief testing on macOS and seems to work as expected. 👍

I also renamed this issue to better reflect the change that has been done.
