### ISSUE TITLE
Only change `@inject-into` if the `@grant` value is valid?

### ISSUE THREAD

**Issue by quoid** [quoid/userscripts#307]
Take the following userscript for example:

```js
// ==UserScript==
// @name        NewScript-fg00n069
// @description This is your new file, start writing code
// @match          *://*/*
// @grant            foo
// @inject-into   auto
// ==/UserScript==

console.log("bar")
```

The `@grant` value is invalid, but because it has an `@grant`, the `@inject-into` will be set to `content`. It might make sense to check *if the `@grant` value is valid` before changing the `@inject-into`.

related #265

**Comment by quoid** [comment]
**Also only use `grant` in `GM.info.script` object** - currently the keys `grant` and `grants` both appear.

**Comment by scholtzm** [comment]
Personally, I think a much better solution would be to change the context and display warning message that the requested `@grant` was not provided. From my experience, this type of logic where "A changes to B, but only if C is not D" usually leads to cryptic errors that are hard to debug.

Also semantically, there's a difference between `@grant unsafeWindow` (valid but not possible in Userscripts) and `@grant foo` (does not exist anywhere).
Another case -- what would happen if valid and invalid `@grant`s are provided?

**Comment by quoid** [comment]
@scholtzm 

> Personally, I think a much better solution would be to change the context and display warning message that the requested @grant was not provided.

Are you suggesting we expand the current warning to include which `@grant`s caused the context change?

> From my experience, this type of logic where "A changes to B, but only if C is not D" usually leads to cryptic errors that are hard to debug.

This is a valid point, but I'd want to reduce the number of compatibility issues, as noted in #305

> Another case -- what would happen if valid and invalid @grants are requested?

This is somewhat related to the quote above as well (ie. reducing the complexity), but the implementation I was thinking of was quite simple.

The [current implementation in the beta build](https://github.com/quoid/userscripts/blob/4c2d8fe79ec5979e4594e49a2d381f5213a3d644/extension/Userscripts%20Extension/Resources/background.js#L416) is:

```js
const grants = userscript.scriptObject.grants; // <---------
const injectInto = userscript.scriptObject["inject-into"];
// prepare the api string
let api = `const US_uid = "${uid}";\nconst US_filename = "${filename}";`;
// all scripts get access to US_info / GM./GM_info, prepare that object
const scriptData = {
    "script": userscript.scriptObject,
    "scriptHandler": scriptHandler,
    "scriptHandlerVersion": scriptHandlerVersion,
    "scriptMetaStr": userscript.scriptMetaStr
};
api += `\nconst US_info = ${JSON.stringify(scriptData)}`;
api += "\nconst GM_info = US_info;";
gmMethods.push("info: US_info");
// if @grant explicitly set to none, empty grants array
if (grants.includes("none")) {
    grants.length = 0;
}
// @grant exist for page scoped userscript
if (grants.length && injectInto === "page") {
    // remove grants
    grants.length = 0;
    // provide warning for content script
    userscript.warning = `${filename} @grant values changed due to @inject-into value`;
}
// @grant exist for auto scoped userscript
if (grants.length && injectInto === "auto") {
    // change scope
    userscript.scriptObject["inject-into"] = "content";
    // provide warning for content script
    userscript.warning = `${filename} @inject-into value changed due to @grant values`;
}
// loop through each @grant for the userscript, add methods as needed
for (let j = 0; j < grants.length; j++) {
    // add methods here
}
```

As you can see above, it's a really basic implementation. We get the `@grant` values and check if any are present. If so, `@grant` or `@inject-into` is manipulated. 

To make the change suggested in this issue, we could simply filter out invalid grant values from `const grants = userscript.scriptObject.grants;` from a [set/array of valid grant values](https://github.com/quoid/userscripts/blob/4c2d8fe79ec5979e4594e49a2d381f5213a3d644/src/page/utils.js#L142), either in this `background.js` file or [on the swift side](https://github.com/quoid/userscripts/blob/4c2d8fe79ec5979e4594e49a2d381f5213a3d644/extension/Userscripts%20Extension/Functions.swift#L1292) before the grants are passed to `background.js`. 

That way, when the check is run to determine whether or not to change `@grant` or `@inject-into` *only* valid grant values with be present.

**Comment by scholtzm** [comment]
> This is a valid point, but I'd want to reduce the number of compatibility issues, as noted in https://github.com/quoid/userscripts/issues/305 - I think it could be a very simple change (more on this below).

Basically, what I was hinting at is a scenario like this:
- script author uses unsupported `@grant` value or just makes a typo
- scope is changed
- completely different error occurs in the script, related to switched context
- no warning about unsupported `@grant` is shown in the console

Needless to say, if compatibility is the main concern, the proposed solution makes sense.

**Comment by quoid** [comment]
done in https://github.com/quoid/userscripts/commit/9c7066f70482cb432247b883a10a7b68d8dad3c6
