### ISSUE TITLE
Top-Level awaits do not work.

### ISSUE THREAD

**Issue by DBa2016** [quoid/userscripts#312]
_System Information:_
> iOS version: iPadOS 15.6.1
> Userscripts version: 1.2.3
> Safari version: not changeable on iPad
> Is this issue related to script injection? yes
> Did the test script (pasted above) successfully run on your machine? not tried, see below

It looks like "await" on top level prevents the script from running entirely. Following statement works:
`var semaphores = GM_getValue("semaphores","{}");`

The async pendant doesn't:
`var semaphores = await GM.getValue("semaphores","{}");`

If there is a top-level await, even statements before that await are not executed (I entered a window.alert there, for easy visibility).

**Comment by quoid** [comment]
@DBa2016 can you provide an example userscript?

**Comment by DBa2016** [comment]
````
// ==UserScript==
// @name A E5
// @namespace http://tampermonkey.net/
// @version 0.3.18
// @description try to take over the world!
// @author DBa
// @match <put your test website here>
// @grant unsafeWindow
// @grant GM.addStyle
// @grant GM.setValue
// @grant GM_getValue
// @grant GM.getValue
// @grant GM.notification
// @grant GM.deleteValue
// @grant GM.xmlHttpRequest
// @grant GM_openInTab
// @grant GM_info
// @noframes
// @require https://releases.jquery.com/git/jquery-3.x-git.min.js
// @require https://code.jquery.com/ui/1.13.1/jquery-ui.min.js
//
// ==/UserScript==

window.alert(`Agent: ${navigator.userAgent}`);
if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
    alert(`Mobile: ${navigator.userAgent}`);
}


// works, an alert is shown (actually two of them) when executing:
var $ = window.jQuery, semaphores = GM_getValue("semaphores","{}");
// doesn't work:
semaphores = await GM,getValue("semaphores","{}");
````

Yes, this is essentially part of a real script, which I am trying to make work in both Tampermonkey and Userscripts (I wrote it for Tampermonkey originally).
Try to run the script as it is (just adjust the @match line), and it will not do anything. Now, comment out the last line and you will see two popups when loading.

**Comment by quoid** [comment]
Thank you for reporting this, @DBa2016. There's a couple things going on here.

1) Top level `await` is invalid unless you wrap the code in an `async` IIFE like: `(async () => {...})();` - the code that is injected is wrapped in a **non-async IIFE**. Is part of this issue a request to always wrap the injected code in an **async IIFE**?

Here's an example:

```js
// ==UserScript==
// @name        NewScript-m670fuqq
// @description This is your new file, start writing code
// @match       *://*/*
// @grant       GM.getValue
// ==/UserScript==


(async () => {
    console.log(123);
    const val = await GM.getValue("val","no value present");
    console.log(val);
})();
```
---
2) Nothing is executed in the script you linked because it's invalid Javascript. This seems to *indicate another issue*. When injecting into the content script context, which is *all userscripts* with `GM` apis, the code is `eval`ed in that context. If you `eval` invalid Javascript, an error **should be** logged, but it is not.

If I wrap [that `eval` call](https://github.com/quoid/userscripts/blob/e29d0a7db51a4c4f61c8a1206f2e1d635d670eac/extension/Userscripts%20Extension/Resources/content.js#L99) in a `try catch`, it does properly log the error. I am unsure why I need to do that, but I will test more and if needed, make the change.

**Comment by DBa2016** [comment]
I just noticed I wrote "GM-comma-getvalue" here rather than "GM-dot-getValue" - this is of course a typo (here only, the script was correct).
In the meantime, I indeed wrapped this in a setTimeout call: `setTimeout(async () => {..});` and it works now.

The original script - which I wrote for Tampermonkey - works without this wrapping, but since the workaround still works in TM, too, I am okay.

How can I receive debug output in iOS?

**Comment by quoid** [comment]
> this is of course a typo

Yeah I figured it was a typo, I just used the `GM.` one as you saw.

> In the meantime, I indeed wrapped this in a setTimeout call: setTimeout(async () => {..}); and it works now.

> The original script - which I wrote for Tampermonkey - works without this wrapping, but since the workaround still works in TM, too, I am okay.

Tampermonkey might wrap everything in an `async` IIFE by default. I am wondering if we should do that here, just to cover these cases.

> How can I receive debug output in iOS?

You'd need to plug your phone in to a macOS computer and look at the output of the console through Safari. It's not ideal. There's some issues regarding this already and I'm hoping to overhaul the popup and give it an output/console view. https://github.com/quoid/userscripts/issues/279

**Comment by quoid** [comment]
I do not believe we will wrap the injected code in an `async` IIFE. Wrapping top level `await` functions is up to the userscript author. Further, the editor properly logs warnings/errors when `await` keywords are used outside of an `async` wrapper or function which should direct authors properly.
