### ISSUE TITLE
Does this extension support GM Scripts?

### ISSUE THREAD

**Issue by quoid** [quoid/userscripts#33]
This question gets asked a lot around here, so I've decided to make a clear issue about it and leave it open.

*Currently*, this extension *can support some* userscripts that use the [Greasemonkey API](https://wiki.greasespot.net/Greasemonkey_Manual:API), but it will **likely** take work from the user to get these scripts to run properly.

This extension does **not** support GM metadata or GM methods.

Implementing support for this is being seriously considered, along with a host of other feature requests.

**Comment by code-guru** [comment]
Thanks for sharing this, it's awesome :-)
I need to have several scripts and choose on which websites each script run, is it part of this issue? Do you have any plan to add this feature?

**Comment by quoid** [comment]
> Do you have any plan to add this feature?

Yes, I plan to, but I do not have a timeline/estimate for when that will happen.

**Comment by quoid** [comment]
closing this thread, with v2.0 it will support *some* GM metablock functionality and likely more to come in future releases - see #37
