### ISSUE TITLE
Save extension settings to `browser.storage`

### ISSUE THREAD

**Issue by ACTCD** [quoid/userscripts#331]
Ref: https://github.com/quoid/userscripts/issues/264#issuecomment-1145544592

Current extension settings and index information, etc. are stored in:
`~/Library/Containers/com.userscripts.macos.Userscripts-Extension/Data/Documents/manifest.json`

It writes to the filesystem through a native application layer (Swift) proxy.

Saving them rescheduled to `browser.storage.local` has many benefits:

- Directly use the browser extension storage API to reduce extension complexity.
- The settings can be directly read in the content script, reducing a layer of message relay.
- Prepare scripts, indexes and other information in advance to [improve the injection speed](https://github.com/quoid/userscripts/issues/184).
- Use its asynchrony to improve interface response and access flexibility.
- Store script update information and [persist update check data for front-end use](https://github.com/quoid/userscripts/issues/278#issuecomment-1174188681).

**Comment by quoid** [comment]
This would be a major improvement. The use of `manifest,json` comes from previous versions where we didn't have access to the WebExtension API. This would further reduce the number of disk read/writes which is an overall good thing.
