### ISSUE TITLE
Safari Extension State Unknown 

### ISSUE THREAD

**Issue by 80608989** [quoid/userscripts#348]
Safari 14.1.2，userscripts Safari version 4.2.3
![image](https://user-images.githubusercontent.com/46585088/195301473-5613427d-873a-498c-9c6e-941be79a9bb2.png)

![C3F6E083-1237-44CC-9F43-8F7DEB0C6CBA](https://user-images.githubusercontent.com/46585088/195301193-447b8f1d-cc00-47ea-841b-764b28b50b26.png)

**Comment by quoid** [comment]
Please see this issue: https://github.com/quoid/userscripts/issues/193

**Comment by 80608989** [comment]
> Please see this issue: #193

thank you ！
