### ISSUE TITLE
Please add a little bit of documentation

### ISSUE THREAD

**Issue by turkishmaid** [quoid/userscripts#349]
_System Information:_
> macOS or iOS version: 12.5.1
> Userscripts version: 4.2.3
> Safari version: 15.6.1
> Is this issue related to script injection? no
> Did the test script (pasted above) successfully run on your machine? yes

Please add a little bit of documentation about how to use the extension.

 It's easy to understand with the video link 
- [x] how to find it, 
- [x] operation is more or less straightforward, 
- [ ] but placed in front of the editor I have no clue what to do now.

Questions are like...
- How to require e.g. jquery?
- What will the `GM.*` methods actually do, what to fill in and what to get out?
- What is `@grant` supposed to be (which is mentioned first in the API) and how to use it?
- How to debug a script (integration with console debugger)?
- ...

Not sure whether this should be discussion instead but, well, giving it a try here :)

**Comment by quoid** [comment]
@turkishmaid 

> Questions are like...

> How to require e.g. jquery?
> What will the GM.* methods actually do, what to fill in and what to get out?
> What is `@grant` supposed to be (which is mentioned first in the API) and how to use it?
> How to debug a script (integration with console debugger)?


Besides the basic app/extension setup documentation, I do think there is a basic userscript knowledge assumption. What I mean by this is we don't attempt to educate users on *how to create basic userscripts*, rather we assume they already know how to do this. 

This is probably not true for all users and pointing them in the right direction for getting that knowledge might be beneficial. On the desktop app we already link them to to this repository through the `Settings` modal, but iOS we do no such thing.

I think we could add more info to the `README` which points users to good walk tutorials/info and continue to link to the readme from the extension. Here are a couple of good resources:

- https://wiki.greasespot.net/Greasemonkey_Manual
- https://violentmonkey.github.io/guide/creating-a-userscript/

> Not sure whether this should be discussion instead but, well, giving it a try here :)

It's ok here, but there's already an open issue that is related.

https://github.com/quoid/userscripts/issues/172

**Comment by turkishmaid** [comment]
Hey, @quoid, thanks for quick response :)

Peeking into GM or VM docs is, of course, the first move, and that's what I did. But it does not help too much. Consider for example jQuery: VM points to `VM.observe()` for jQuery integration, but docs here don't mention that a `GM.observe()` or so exists. Can I `@require` [VM/dom](https://violentmonkey.github.io/guide/observing-dom/#requirements)? Who knows. Maybe I have to use a pattern advertised for GM (from StackOverflow, because GM docs are about the worst in the wild)? Let's try it out, somehow it will work. As developers we love fiddling, don't we. But I rather wanted to take up the fight with the hosting page, not so much with my toolbox ;)

Regarding **what** to be documented, my suggestion was not so much to explain about the user script itself (that's JavaScript, nuff said), but about what API the script actually has towards the hosting page, specific to exactly this tool I have installed, rather than sending me to google whether docs of other user script tools might reveal something that would also work here. A simple example for each API function would also great, sometimes even sufficient.

It was just meant as a suggestion to make your great effort more accessible for others. No offense, sorry for bringing it up.

**Comment by quoid** [comment]
I understand, the documentation needs improvement. You make a good point about pointing people to other documentation, as some of it does not apply to this app/extension.

> It was just meant as a suggestion to make your great effort more accessible for others. No offense, sorry for bringing it up.

This is well received and I agree it needs improvement. I am hoping me or someone looking to contribute can get around to it soon.
