### ISSUE TITLE
Script not working in safari browser

### ISSUE THREAD

**Issue by CODE-LA-LI-LU-LE-LO** [quoid/userscripts#350]
_System Information:_
> macOS or iOS version: ipadOs 15.6.1
> Userscripts version: v1.2.3
> Safari version: 15
> Is this issue related to script injection? yes
> Did the test script (pasted above) successfully run on your machine? yes

(This article was typed using a translator.)

https://github.com/erickRecai/Replace-Text
I'm trying to use that script. But adding arbitrary keywords to 'replaceRules' inside the script didn't work either.
(This script worked on Google Chrome with tampermonkey)
I'm not good at Javascript, so I couldn't figure out what the problem was.
Can you tell me what is the problem?

**Comment by quoid** [comment]
@CODE-LA-LI-LU-LE-LO 

Please provide a usage example for the user script. For example, providing a url where it should function with steps on how to use it and the expected outcome.

**Comment by CODE-LA-LI-LU-LE-LO** [comment]
@quoid 

![image](https://user-images.githubusercontent.com/8914838/196324453-69d150d0-a890-4157-963a-630a1fdda534.png)
Added '[/issue(?=[A-z])/i,"is replaced!"]' to line 109 of the Replace Text.user.js script.
The fix should change 'issues' to 'is replaced!s' when this issues page is refreshed.
![image](https://user-images.githubusercontent.com/8914838/196324391-9e803ec2-e7b7-4dfe-9f10-a3bae2b58fa3.png)

**Comment by quoid** [comment]
I am not sure I follow, does the userscript work now?

**Comment by CODE-LA-LI-LU-LE-LO** [comment]
When an alert statement is inserted, a message popup is displayed in safari.  The script is working.  However, the js function does not work (it works normally in chrome).

**Comment by quoid** [comment]
This userscript uses `unsafeWindow` which does not exist in Safari. You can look at [this issue](https://github.com/quoid/userscripts/issues/252) for more information.

To get this to work you can do one of the following:

1) On line `25` add: `const unsafeWindow = window;`

**OR**

2) On line `125` change `if (unsafeWindow.globalListName) {` to `if (typeof unsafeWindow != "undefined" && unsafeWindow.globalListName) {`

This is really an issue with the userscript and the dev could add this check (option `2`) to their userscript.

**Comment by CODE-LA-LI-LU-LE-LO** [comment]
Thank you! I’m greatful for your help!
