### ISSUE TITLE
Safari Extension State Unknown

### ISSUE THREAD

**Issue by jpillora** [quoid/userscripts#353]
_System Information:_
> macOS or iOS version: 12.6
> Userscripts version: 4.2.3 (59)
> Safari version: Version 16.0 (17614.1.25.9.10, 17614)

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/633843/197184558-a3af8567-c240-4a68-8dc2-ca76d5f5176a.png">

Userscripts used to work, though now it seems Safari can't even see it. User scripts reports "Safari Extension State Unknown"

**Comment by jpillora** [comment]
Thanks, ahh was searching open issues

For others, 
1. Quit Safari
2. Run `/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f -R /Applications/Safari.app`
3. Open Safari
4. Should prompt to enable

**Comment by quoid** [comment]
thanks for the steps @jpillora - I am going to quote it in the other issue
