### ISSUE TITLE
@require can't work well after upgrading to 4.3.0

### ISSUE THREAD

**Issue by 4ooc** [quoid/userscripts#355]
```
// @require      https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/nprogress/0.2.0/nprogress.min.js
// @require      https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/clipboard.js/2.0.10/clipboard.min.js
```
Above files use  the  keywords `this`, but it's always undefined when script injection.

I found the latest changes that make the scripts run in strict mode, and @require also in strict mode .
https://github.com/quoid/userscripts/blob/479eff54498da77f260229bd115295ca7e965aa6/extension/Userscripts%20Extension/Resources/content.js#L244

**Comment by quoid** [comment]
@4ooc 

Thanks for reporting the issue. When I `@require` one of those `js` files, I can see the error. I believe I have a fix for this.

Would it be possible to provide a test userscript for this issue? Perhaps something that includes one of those `@require` values and a simple a test? I am not sure what those required libraries are supposed to do.

Thank you

**Comment by 4ooc** [comment]
```
// ==UserScript==
// @name        NewScript-i999ds1t
// @description This is your new file, start writing code
// @match       *://*/*
// @require     https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/nprogress/0.2.0/nprogress.min.js
// ==/UserScript==

$('head').append("<style>#nprogress{pointer-events:none}#nprogress .bar{background:#f44444;position:fixed;z-index:1031;top:0;left:0;width:100%;height:2px}#nprogress .peg{display:block;position:absolute;right:0;width:100px;height:100%;box-shadow:0 0 10px #f44444,0 0 5px #f44444;opacity:1;-webkit-transform:rotate(3deg) translate(0,-4px);-ms-transform:rotate(3deg) translate(0,-4px);transform:rotate(3deg) translate(0,-4px)}#nprogress .spinner{display:block;position:fixed;z-index:1031;top:15px;right:15px}#nprogress .spinner-icon{width:18px;height:18px;box-sizing:border-box;border:solid 2px transparent;border-top-color:#f44444;border-left-color:#f44444;border-radius:50%;-webkit-animation:nprogress-spinner .4s linear infinite;animation:nprogress-spinner .4s linear infinite}.nprogress-custom-parent{overflow:hidden;position:relative}.nprogress-custom-parent #nprogress .bar,.nprogress-custom-parent #nprogress .spinner{position:absolute}@-webkit-keyframes nprogress-spinner{0%{-webkit-transform:rotate(0)}100%{-webkit-transform:rotate(360deg)}}@keyframes nprogress-spinner{0%{transform:rotate(0)}100%{transform:rotate(360deg)}}</style>");
NProgress.start();
process=0
iv=setInterval(()=>{
  NProgress.set(process/100)
  console.log(process)
  if(process>=100){
    clearInterval(iv)
  }
  process+=10
}, 500)
NProgress.done();
```
<img width="1470" alt="2022-10-25 00 56 39" src="https://user-images.githubusercontent.com/22727824/197582725-5c1f6e60-19ac-44df-b741-d5d76b179f25.png">

Like this?

**Comment by quoid** [comment]
@4ooc 

> Like this?

I think there might be some errors in that javascript and maybe should also `@require` jquery?

> process=0 
> iv=setInterval

Both `process` and `iv` and `undefined`. I can add:

`var process=0` & `iv=setInterval` and `@require` jquery to get it to function.

**Comment by 4ooc** [comment]
> @4ooc
> 
> > Like this?
> 
> I think there might be some errors in that javascript and maybe should also `@require` jquery?
> 
> > process=0
> > iv=setInterval
> 
> Both `process` and `iv` and `undefined`. I can add:
> 
> `var process=0` & `iv=setInterval` and `@require` jquery to get it to function.

Sorry, I could't run script with `@require` nprogress.min.js via userscripts extension now. So  I run it via another extension.

**Comment by quoid** [comment]
@4ooc all good, hotfix should be landing on the app store once it gets approved by apple
