### ISSUE TITLE
iPad os

### ISSUE THREAD

**Issue by seasaltseasalt** [quoid/userscripts#36]
Hello, is there a way I am get this onto my iPad os? iPad OS gives us  desktop safari on iPad. When I click the link to Apple App Store, the get icon is shaded it.

Thankyou for your help

**Comment by quoid** [comment]
@seasaltseasalt 

There is currently no iPad or iPhone version.

At the current moment, there aren't plans to develop it for those platforms. The reason is because Safari for iOS / iPadOS does not support extensions, only content blockers.
