### ISSUE TITLE
Cannot apply more than one userstyle

### ISSUE THREAD

**Issue by remino** [quoid/userscripts#368]
_System Information:_
> macOS or iOS version: macOS 12.6
> Userscripts version: 4.3.2
> Safari version: 16.0
> Is this issue related to script injection? Related to userstyle injection, not script.
> Did the test script (pasted above) successfully run on your machine? See below.

Since a recent update of Userscripts, it seems that only one userstyle can be applied per site. Trying to apply more than one will disable all of them.

**Comment by quoid** [comment]
thank you for reporting this, i found the bug and made a PR

next patch version, which should go out soon, will include this fix, until then you could use `GM.addStyle` method and a javascript file. https://github.com/quoid/userscripts#api

**Comment by remino** [comment]
In my case, it can wait. Thank you for looking into this!
