### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by quoid** [quoid/userscripts#37]
It's been a while since I've updated this extension and wanted to give an update to anyone interested.

In the months since the last update, [more established and feature rich userscript extensions](https://www.tampermonkey.net/?browser=safari) have come to the app store. I thought a lot about what to do next with this extension and if I should put time into creating a new update.

Even though I don't imagine this extension will ever have the same amount of features as the more established userscript managers (nor do I think I want that), I decided I would address some specific pain points I, and others, have with the version 1.x.x.

I've been *slowly* developing version 2 since I made that decision. The biggest pain point I've heard from users (and experienced myself) is the lack of support for multiple, *domain specific* userscripts. I am am addressing this and some other things with a version 2 update.

I am hoping to push the version 2 update in the near future (~ 1-2 months). If anyone is interested in beta testing, please let me know in this issue.

I will **not** be abandoning version 1.x.x. When version 2 comes out, I will be pushing version 1.x.x to the app store as a new/separate app under a new name (TBD). I am doing this because I have heard from some users that they do not need nor want more advanced userscript functionality.

Below you can check out a screenshot of the current build I've been testing on my machine.

<img width="1241" alt="Screen Shot 2020-03-24 at 22 10 25" src="https://user-images.githubusercontent.com/7660254/78567415-a6a56380-77ee-11ea-91be-6700dc0445c8.png">

**Comment by v7rzlhb3xg** [comment]
Looks fantastic, very interested in beta testing!

**Comment by quoid** [comment]
@v7rzlhb3xg 

I am working on fixing on annoying bug, then I think the build will be ready. Email me at justin [at] k21p.com and I can make sure you get a build when it's ready.

**Comment by piacimosca** [comment]
I would hopp on the beta train as well.

**Comment by quoid** [comment]
@piacimosca shoot me an email at the address above and I will put you on the list

**Comment by michaelgosling** [comment]
Also interested in this beta.

**Comment by aihkas** [comment]
Interested in this beta! great work!

**Comment by quoid** [comment]
@aihkas the more the better - please email at [the address above](https://github.com/quoid/userscripts/issues/37#issuecomment-615002458) and I will send you a build

**Comment by quoid** [comment]
Thank you everyone who reached out to me. I am no longer looking for more beta testers, but version 2 will be released on the app store *soon*.
