### ISSUE TITLE
iOS New function support

### ISSUE THREAD

**Issue by Hao0920** [quoid/userscripts#398]
In order to facilitate sorting, I hope to support reading the contents of subfolders under directory files. Thank you.

**Comment by Hao0920** [comment]
I put the script on iCloud for synchronization. The path is "file:///private/var/mobile/Library/Mobile%20Documents/com~apple~CloudDocs/Userscripts/" but want to pass the function/author To organize the script, it will be placed at file:///private/var/mobile/Library/Mobile%20Documents/com~apple~CloudDocs/Userscripts/ Authorname/" or "file:///private/var/mobile/Library/Mobile%20Documents/com~apple~CloudDocs/Userscripts/Baiduplus”

**Comment by Hao0920** [comment]
Thanks, I can try it. Because my scripts are all obtained from the Internet. It also includes your script. The only worry is whether to replace the content or re-download a new script if it is updated.  : )

**Comment by quoid** [comment]
@Hao0920 

Good point. If a userscript is updated remotely, and the `@name` value is different from the `filename` it would save a new copy with the `@name` value and remove the previous.

**Comment by Hao0920** [comment]
So back to origin: in order to facilitate sorting, I want to support reading the contents of subfolders under directory files.
 : ) : ) : ) : ) : )
So I can constraint the problem by the folder.

**Comment by quoid** [comment]
@Hao0920 

it might be easier to allow `filename` and `@name` to be different

**Comment by Hao0920** [comment]
Maybe you're right..
But it's pretty hot to encounter this:
[https://greasyfork.org/en/scripts/437781](https://greasyfork.org/en/scripts/437781-%E8%B6%85%E6%98%9F-%E5%AD%A6%E4%B9%A0%E9%80%9A%E7%BD%91%E8%AF%BE%E5%B0%8F%E5%8A%A9%E6%89%8B-%E4%BF%AE%E5%A4%8D%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE-%E8%87%AA%E5%8A%A8%E8%B7%B3%E8%BD%AC%E4%BB%BB%E5%8A%A1%E7%82%B9-%E7%AB%A0%E6%B5%8B%E4%BD%9C%E4%B8%9A%E5%AD%97%E4%BD%93%E8%A7%A3%E5%AF%86-%E8%87%AA%E5%8A%A8%E7%AD%94%E9%A2%98-%E9%A2%98%E5%BA%93%E8%A6%86%E7%9B%96%E7%8E%87%E9%AB%98-%E5%AE%8C%E5%85%A8%E5%85%8D%E8%B4%B9)
[https://greasyfork.org/en/scripts/370634](https://greasyfork.org/zh-CN/scripts/370634-%E6%87%92%E4%BA%BA%E4%B8%93%E7%94%A8-%E5%85%A8%E7%BD%91vip%E8%A7%86%E9%A2%91%E5%85%8D%E8%B4%B9%E7%A0%B4%E8%A7%A3%E5%8E%BB%E5%B9%BF%E5%91%8A-%E5%85%A8%E7%BD%91%E9%9F%B3%E4%B9%90%E7%9B%B4%E6%8E%A5%E4%B8%8B%E8%BD%BD-%E7%9F%A5%E4%B9%8E%E5%A2%9E%E5%BC%BA-%E7%9F%AD%E8%A7%86%E9%A2%91%E6%97%A0%E6%B0%B4%E5%8D%B0%E4%B8%8B%E8%BD%BD-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%9B%B4%E6%8E%A5%E4%B8%8B%E8%BD%BD%E7%AD%89%E5%A4%9A%E5%8A%9F%E8%83%BD%E5%B7%A5%E5%85%B7%E7%AE%B1-%E5%8A%9F%E8%83%BD%E5%8F%AF%E7%8B%AC%E7%AB%8B%E5%BC%80%E5%85%B3-%E9%95%BF%E6%9C%9F%E6%9B%B4%E6%96%B0-%E6%94%BE%E5%BF%83%E4%BD%BF%E7%94%A8-v6)

**Comment by Hao0920** [comment]
I see. Thank you very much for your explanation.
