### ISSUE TITLE
Is debugging possible?

### ISSUE THREAD

**Issue by taozhiyu** [quoid/userscripts#408]
I don't know if it's possible to link remotely with vscode or chrome DevTools or other editors to debug the code?

My scripts work fine in tampermonkey but don't respond in this plugin, I don't know how to locate the exception.

Hope to get an answer soon~

**Comment by quoid** [comment]
@taozhiyu 

It is certainly possible to debug, but I am curious what it is you are trying to debug? 

> I don't know if it's possible to link remotely with vscode or chrome DevTools

I don't know what you mean by 'link remotely with vscode'. This extension is made for Safari so unsure why you would want to use Chrome's dev tools, but that would not be possible.

Here are some tips:

- Debugging your script should be the first thing you do. Remember that all browser and not equal and everything you can do in chrome or another browser is not always possible in Safari.
- Ensure that you are familiar with which API methods  and metadata keys are available in this extension; all user script managers are not equal - [readme](https://github.com/quoid/userscripts#readme)
- Ensure you've tested basic injection before assuming there is a problem with the extension, it is included in the issue template
- Use safari's dev tools to debug your script and to debug the extension - you can access the extension's background page via `Develop > Web Extension Background Pages > Userscripts` - also remember you can change context in the dev tools console to access the content script context
- Use Apple's `Console.app` and filter for `Userscripts` to look for errors with the app/extension
- This repository contains all of the source code for the project, feel free to load it in your editor of choice/XCode and make a local build to work with

**Comment by taozhiyu** [comment]
> @taozhiyu
> 
> It is certainly possible to debug, but I am curious what it is you are trying to debug?
> 
> > I don't know if it's possible to link remotely with vscode or chrome DevTools
> 
> I don't know what you mean by 'link remotely with vscode'. This extension is made for Safari so unsure why you would want to use Chrome's dev tools, but that would not be possible.
> 
> Here are some tips:
> 
> * Debugging your script should be the first thing you do. Remember that all browser and not equal and everything you can do in chrome or another browser is not always possible in Safari.
> * Ensure that you are familiar with which API methods  and metadata keys are available in this extension; all user script managers are not equal - [readme](https://github.com/quoid/userscripts#readme)
> * Ensure you've tested basic injection before assuming there is a problem with the extension, it is included in the issue template
> * Use safari's dev tools to debug your script and to debug the extension - you can access the extension's background page via `Develop > Web Extension Background Pages > Userscripts` - also remember you can change context in the dev tools console to access the content script context
> * Use Apple's `Console.app` and filter for `Userscripts` to look for errors with the app/extension
> * This repository contains all of the source code for the project, feel free to load it in your editor of choice/XCode and make a local build to work with

Well since I only have a Windows PC and an iPhone, I don't know how to debug in this case, well, it looks like it's not a problem with this plugin. Anyway, thanks for your reply!

Happy New Year!

**Comment by quoid** [comment]
> Well since I only have a Windows PC and an iPhone

That key detail would have changed the length of my reply 🤣

Happy New Year to you as well :)

**Comment by nudefireninja** [comment]
Please elaborate how to debug userscripts. I see "Injecting Google Cookie Consent Popup (js)" in the console but I cannot find my script anywhere in the sources in the inspector (either for the current page or the extension's background page). Specifically, how can I set breakpoints? Thanks.

**Comment by quoid** [comment]
@nudefireninja review this issue: https://github.com/quoid/userscripts/issues/409

> cannot find my script anywhere in the sources in the inspector

Where are looking exactly?

Below is an example of viewing a script in dev tools. Injected scripts are not always in that exact spot, but if they are properly injected, you would see them in that sidebar and possibly in a subfolder. You add breakpoints as you normal would.

Further you have access to the extension injected script,`content.js`, in that sidebar, so you could also add breakpoints to that see why injection is not happening. 

<img width="1255" alt="Screen Shot 2023-01-14 at 3 05 50 PM" src="https://user-images.githubusercontent.com/7660254/212494277-94331496-0cf7-44d5-a7c7-0abdf88d77c0.png">

**Comment by nudefireninja** [comment]
@quoid Thanks. I didn't look there.

![infinity-facepalm](https://user-images.githubusercontent.com/6565746/212982450-a624b480-a4ab-45ca-8d7f-d3fb17dbfa92.gif)
