### ISSUE TITLE
Implement Metadata Block from Greasemonkey API

### ISSUE THREAD

**Issue by luciomartinez** [quoid/userscripts#41]
UserScripts have at the top a block to set the metadata. When a UserScript manager parses the UserScript, reads this block to do things like:

- Filter websites where the script can be ran
- Fetches any requirement (external lib)
- Identifies script (useful when multiple scripts are managed)

As you can see, the implementation of "just the metadata block" involves quite lot of features at the same time. Each feature may be looks by its own. Some of these may be included in a v2 and some in a v3 (if they even happen).

I just wanted to flag these topics so they can be discussed and users (of this plugin) can notice what's the priority around them.

**Comment by quoid** [comment]
I am closing this issue. Please keep issues focused to specific feature enhancements, feedback or help.

**Comment by luciomartinez** [comment]
It was easier to say that this was gonna be implemented on v2... Thx 👍
