### ISSUE TITLE
Weird GM_ problems

### ISSUE THREAD

**Issue by Delamcode** [quoid/userscripts#423]
Why does [this](https://github.com/adamlui/userscripts/blob/master/chatgpt/duckduckgpt/duckduckgpt.user.js) not work? According to the [author](https://github.com/adamlui/userscripts/issues/10) it seems GM_ functions do not work, but it lists them as supported under the api in the readme. I am using an iPad for this, and do not have access to a mac.

**Comment by Delamcode** [comment]
For the record, I’m fine with editing the script, as long as I understand what the problem is…

**Comment by quoid** [comment]
`GM_` api methods are not supported - check out [the readme](https://github.com/quoid/userscripts#api).

**Comment by Delamcode** [comment]
What is the difference between GM_ and GM.?

**Comment by quoid** [comment]
@Delamcode posting that information in the [other issue](https://github.com/adamlui/userscripts/issues/10) in case the author wants to update their user script.

**Comment by Delamcode** [comment]
I’ve tried switching it to GM. but I still have problems. Give me a minute.

**Comment by Delamcode** [comment]
This is the error:
‘ReferenceError {}
column: 43
line: 87
message: "Can't find variable: GM_registerMenuCommand"
sourceURL: "https://duckduckgo.com/?q=what+is+the+meaning+of+life&t=ipad"
stack: "enableCommandMenu@https://duckduckgo.com/?q=what+is+the+meaning+of+life&t=ipad:87:43↵main@https://duckduckgo.com/?q=what+is+the+meaning+of+life&t=ipad:54:26↵@https://duckduckgo.com/?q=what+is+the+meaning+of+life&t=ipad:112:17↵@https://duckduckgo.com/?q=what+is+the+meaning+of+life&t=ipad:179:3↵@https://duckduckgo.com/?q=what+is+the+meaning+of+life&t=ipad:181:15↵global code@https://duckduckgo.com/?q=what+is+the+meaning+of+life&t=ipad:182:11↵appendChild@[native code]↵injectJS@safari-web-extension://F0435466-F9A8-46C1-B498-8953D9410A63/content.js:274:34↵processJS@safari-web-extension://F0435466-F9A8-46C1-B498-8953D9410A63/content.js:222:21↵@safari-web-extension://F0435466-F9A8-46C1-B498-8953D9410A63/content.js:402:18"
__proto__: Object‘

**Comment by quoid** [comment]
I posted the reasons in the other repo. This is not an issue with this manager because those methods are not supported. It is not up to the user script author, or yourself to update the user script.

Support for the older `GM_` methods has already been requested, so I am closing this issue.
