### ISSUE TITLE
Feature: Support in-App-Browsers on iOS

### ISSUE THREAD

**Issue by dodmi** [quoid/userscripts#430]
Hi,

this extension is great. But it seems not to be working, if an in-App-Browser is used. E.g. I have an rss reader app, which opens the articles inside the app, using Safari (my adblock extension is working).
It would be great, if you could support this scenario, too, so that User Scripts will also work inside apps, which use Safari internally to display web content.

**Comment by dodmi** [comment]
Well, [AdGuard](https://apps.apple.com/us/app/adguard-adblock-privacy/id1047223162) applies also CSS filters even with the built-in WebKit browser and you can generate new CSS rules within the built-in browser.  I'm using the free version without VPN functionality. 
But ok, thank you anyway.

**Comment by quoid** [comment]
@dodmi 

I think part of the distinction is that AdGuard is creating a dynamic [content-blocker](https://developer.apple.com/documentation/safariservices/creating_a_content_blocker) which is system specific and this extension is Safari specific.

Even if we really wanted to implement this, it's not currently possible with Apple web extension API.

**Comment by quoid** [comment]
> Do you think content blocker works with built-in WebKit browsers of 3rd party Apps? I think it should only work in Safari browser.

For some reason I thought they were system wide, but just checked my phone and they are loaded as an extension, so I am probably wrong.

I wonder how AdGuard accomplishes this without VPN 🤔

**Comment by dodmi** [comment]
Here are the requested screenshots. As my only other extension is Adguard (for years), I never wondered about that…

I can open Adguard in the actions menu and then select the element, which I‘d like to hide.

![98109AC8-9F3F-46BE-9261-787EDACE8767](https://user-images.githubusercontent.com/4572946/222047921-15e12d57-88ae-4741-9e2a-ee037c936c1f.jpeg)
![420F5904-43C0-44A0-91FC-0D98D3136B0D](https://user-images.githubusercontent.com/4572946/222047935-39fd4aa7-7929-4773-a36e-e1baeed485f8.jpeg)
![1BD70500-E496-4CC5-B11A-C6554948A6D1](https://user-images.githubusercontent.com/4572946/222047939-dbfccb12-17ab-44f2-bd7f-b4f18af379ec.png)
![1A276F36-63AA-4478-B8B5-A9518B3CF2B0](https://user-images.githubusercontent.com/4572946/222047950-00057154-37c5-4bd6-85cf-b6383552ec92.png)

**Comment by dodmi** [comment]
Well, I’m not familiar with the technological background.
The built-in browser is very comfortable, as it makes switching between the feed items really easy. Opening every article in Safari itself (and cleaning up afterwards) is a bit painful. From a user perspective.

Adguard (block and cosmetic) filters apply without interaction, so I thought this is „normal“. The screenshots show, how to define a new rule. Having to click each time is probably also a bit painful - and opening Safari will be a bit faster, since it’s possible directly from the bar.

My aim is to remove Apple’s SmartApp banners. Which means I need to remove the corresponding meta tag from the web page. Adblock supports only hiding, but not removing elements on iOS.

So having a no-click-solution would be cool (from a user perspective). But as I understand, this isn’t a good idea for various reasons.

**Comment by dodmi** [comment]
So, thank you for your input on this issue. I guess, we should close it :)

**Comment by codeninja-ru** [comment]
It would be killer feature. Just for example we could have a fully customizable with userscripts twitter app
