### ISSUE TITLE
[Feature Request] Allow scripts to access local files

### ISSUE THREAD

**Issue by tshu-w** [quoid/userscripts#449]
Hello, thank you for your application. I have noticed that it currently does not seem to support scripts accessing local files. I would like to know if there are any plans to support this feature.

I tried searching through the issues but did not find anything related, so I am submitting this feature request.

**Comment by quoid** [comment]
Thanks for the feature request.

Putting aside whether or not this is technically viable, my immediate reaction is that allowing a user script to read or write to the local file system would be a huge security risk.

**Comment by quoid** [comment]
Can you elaborate on the request and give a usage example?

**Comment by tshu-w** [comment]
I use [Immersive Translate](https://immersive-translate.owenyoung.com) to translate web pages, but it's not applicable for local pages like email subscriptions downloaded through mu4e.

I understand that this may bring risks. As far as I know, Tampermonkey supports this feature but it needs to be enabled separately.

**Comment by theowenyoung** [comment]
Hi, for immersive translate, we plan to support uploading local HTML to translate it. it is available for extension now.

<img width="690" alt="Screenshot 2023-03-16 at 20 21 41" src="https://user-images.githubusercontent.com/62473795/225616202-17322b94-2550-44d0-a225-400e48994cb3.png">

**Comment by tshu-w** [comment]
@theowenyoung Wow, how did you discover this issue? I use Safari and it seems that only scripts can be used.

I tried using a plugin and found that uploading requires dragging files. However, the usual process is to have already opened a local HTML file in the browser and hope to be able to click on translation just like an online page.

**Comment by theowenyoung** [comment]
> @theowenyoung Wow, how did you discover this issue? I use Safari and it seems that only scripts can be used.

Someone send me this issue! haha!
 
> I tried using a plugin and found that uploading requires dragging files. However, the usual process is to have already opened a local HTML file in the browser and hope to be able to click on translation just like an online page.

yes, I agree that translating the local HTML directly is a better experience. but some browsers like Firefox does not provide the ability to access local file, so we must do it manually.

**Comment by tshu-w** [comment]
> yes, I agree that translating the local HTML directly is a better experience. but some browsers like Firefox does not provide the ability to access local file, so we must do it manually.

It seems that many browsers do not support it due to security concerns, and it is unclear whether Safari supports it.

@quoid If Safari does not support it, feel free to close this issue.

**Comment by quoid** [comment]
@tshu-w I should have elaborated that reading and writing the local file system can be risky, but we do allow it for saving user scripts.

I think I understand the request better now. Please correct me if I am wrong, but you'd like to run the extension when the HTML path is `file"//`?

I do not believe this is supported by Safari, but I can not find the specific article in the documentation that states this any longer. Meaning the content script can not be executed unless the uri starts with `http/s`.

I will close this since it does not seem possible, but I understand the value :/
