### ISSUE TITLE
[iOS] Trying to use the extension without setting the script folder in the main app returns "failed to get init data"

### ISSUE THREAD

**Issue by scholtzm** [quoid/userscripts#450]
**Steps:**
1. Do a clean install on iOS
2. Enable the extension for Safari browser
3. Try to install a script
4. You will get error "failed to get init data"

Not sure if the same happens on macOS.

**Expected:**
A more descriptive error that explains the user that they need to launch the main Userscripts app and set the script folder first before installing scripts.

_-or-_

Use *some* folder as default.

**Related in code:**
https://github.com/quoid/userscripts/blob/f2673f2de38648947101e4f38e67ff07a46fb540/xcode/Safari-Extension/SafariWebExtensionHandler.swift#L77

**Comment by quoid** [comment]
Thank you for the report @scholtzm, I am going to close this issue since there is already an open on regarding the improvement of error handling: #279
