### ISSUE TITLE
iOS 1.4.1 displays number of active scripts therefore putting a blue dot in the address bar

### ISSUE THREAD

**Issue by Taxyovio** [quoid/userscripts#474]
![image](https://user-images.githubusercontent.com/38234151/234895058-61a7d6db-9bf8-428d-91d5-5488e71dbc69.jpeg)
I'm not sure if this is intentional or a bug. But the blue dot is very distracting.

Device: iPad Pro 5th gen
System: iPadOS 16.4.1

**Comment by LeoNatan** [comment]
I’m sorry, but why was this changed merged for iOS, without a settings page to be able to disabled it?

mom macOS, there is just a badge on the toolbar item button. Annoying but OK—and most importantly, there is a setting to disable. On iOS, Safari is ridiculous and the extension makes it unusable. Every page with a script makes the blue dot show up, making one guess what happened. I’d even ask, who needs this blue dot? Who wants or needs the badge on iOS, triggering the blue dot? Surely, you could have disabled it by default on iOS, until the settings page is implemented.

**Comment by LeoNatan** [comment]
In fact, I think you are abusing the badge on both iOS and macOS; it’s intended for notifications, not constant, static data.

**Comment by Taxyovio** [comment]
@quoid Can we please re-open this issue? Not sure why it's closed despite no solution was reached.

**Comment by quoid** [comment]
@Taxyovio Yes, I think we should push a patch to disable this until we get a setting page. While I personally like the badge, we want to ensure the users who find it distracting have a way to turn it off.

**Comment by amadejpapez** [comment]
> In fact, I think you are abusing the badge on both iOS and macOS; it’s intended for notifications, not constant, static data. 

Yeah I thought the app wanted me to do something and as I couldn't find anything, thought something was wrong with the app. 😅

**Comment by Citizen2023** [comment]
What static

**Comment by quoid** [comment]
Done, and will be addressed in next patch release: https://github.com/quoid/userscripts/commit/eb797f277b549fa0ec681369ff50638d79f20fdf
