### ISSUE TITLE
Userscripts Settings Not Displaying

### ISSUE THREAD

**Issue by jnbli** [quoid/userscripts#48]
I'm on macOS Mojave and upon clicking the Userscripts </> icon in the toolbar, I see a black screen with "Userscripts Safari" centered in the middle. I don't see any other options.

<img width="1392" alt="Screen Shot 2020-07-11 at 11 58 52 AM" src="https://user-images.githubusercontent.com/19863571/87231765-c78dcf80-c36e-11ea-932e-346f760d9408.png">

**Comment by quoid** [comment]
@jnbli can you open the web inspector's console to see what (if any) errors are being displayed?

**Comment by basicide** [comment]
I'm having the same issue. I only have Userscripts 2.0.0 installed currently. Here's a screenshot of the errors I see when I get that screen.
<img width="298" alt="Screen Shot 2020-07-11 at 5 03 16 PM" src="https://user-images.githubusercontent.com/13152423/87234644-9b874400-c398-11ea-822b-6587f242acf2.png">

**Comment by quoid** [comment]
@basicide Thanks for including the screenshot

Could you tell me your OS version and Safari version?

Would you be willing to take a full screenshot of the browser when this error comes up? And with the web inspector console open, could you try typing in `safari` and see what gets returned (see image attached)?

The error is suggesting that the `safari` object in not reachable.

<img width="1234" alt="Screen Shot 2020-07-11 at 18 38 43" src="https://user-images.githubusercontent.com/7660254/87235067-eb203c80-c3a5-11ea-8e57-4bf806011e5e.png">

**Comment by basicide** [comment]
@quoid I'm on 10.14.6, Safari 12.1.2. Here's the screenshot you requested.
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/13152423/87235147-536b2000-c39e-11ea-91ea-54e227178fd8.png">

**Comment by quoid** [comment]
> I'm on 10.14.6, Safari 12.1.2

Ok, that's what I was thinking was the problem. This version needs safari 13+.

It's tricky because Safari 13 is available for macOS 10.13+, so older operating systems can install the update. However, it is possible that some users with the older operating systems have not updated their version of Safari, which would cause incompatibility (like we are seeing here).

I think I should add an error message that tells users to make sure they are using safari 13+ if the `safari` object is unreachable... or restrict installations.

**Comment by basicide** [comment]
So should this work with Mojave as long as I update to Safari 13?

**Comment by quoid** [comment]
@basicide Yep

**Comment by jnbli** [comment]
Can confirm. Updated to Safari 13 and it works.

**Comment by quoid** [comment]
@jnbli great! I am going to close this issue since it is resolved
