### ISSUE TITLE
iOS app shows a false notification dot in Safari

### ISSUE THREAD

**Issue by moenodedev** [quoid/userscripts#492]
Userscripts adds a blue notification dot to the Safari address bar.

**Comment by quoid** [comment]
See: https://github.com/quoid/userscripts/issues/474

**Comment by moenodedev** [comment]
The badge was intentional? https://github.com/quoid/userscripts/blob/eb797f277b549fa0ec681369ff50638d79f20fdf/xcode/Safari-Extension/Resources/background.js#L83-L130

Please remove the false badge or the extension will be reported.

**Comment by quoid** [comment]
I included a link to the issue where all of this is covered, including the question you just asked.
