### ISSUE TITLE
Fix naming conventions

### ISSUE THREAD

**Issue by quoid** [quoid/userscripts#5]
.

**Comment by quoid** [comment]
**Remove "Extension" from extension name**
<img width="534" alt="Screen Shot 2019-05-02 at 3 27 20 PM" src="https://user-images.githubusercontent.com/7660254/57101366-1366d280-6cef-11e9-882b-aa5da91315f2.png">

**Comment by quoid** [comment]
- **change "organization" to "Userscripts", instead of k21p**
<img width="408" alt="Screen Shot 2019-05-02 at 3 31 59 PM" src="https://user-images.githubusercontent.com/7660254/57101561-82dcc200-6cef-11e9-8b5a-9a12b179d936.png">

**Comment by quoid** [comment]
- on first load, only set editor message to "Last edited on" if saved code exists

`Line 49` in `SafariExtensionViewController.swift`

**Comment by gingerbeardman** [comment]
>- **Remove "Extension" from extension name** ...

This is easy. 

Not sure about the "by" line

**Comment by quoid** [comment]
> Not sure about the "by" line

Agreed, it could stay as is
