### ISSUE TITLE
App releases on Github

### ISSUE THREAD

**Issue by abrala** [quoid/userscripts#50]
Any plans to push the downloadable .app versions here?

**Comment by quoid** [comment]
I didn't plan on it. I made the app available in all countries and regions.

Any particular reasons for making a direct download?

**Comment by abrala** [comment]
For people, like me, who don't use Apple ID services and don't have ability to compile from source.

**Comment by ed9w2in6** [comment]
I can't see why this should be done.

As a general comment, I think it is much safer to download from App Store, where they do all the integrity checks and handles updates for you.
Many times, downloading macOS app from website is only going to complicate things.

Are there any reasons for not using Apple ID services?

**Comment by quoid** [comment]
@abrala makes sense, I didn't consider that

I'll put future release on GitHub

**Comment by quoid** [comment]
@abrala you can download from the releases section now, starting with v2.0.1
