### ISSUE TITLE
[artefact] iChat.app symbolic link

### ISSUE THREAD

**Issue by ed9w2in6** [quoid/userscripts#51]
_System Information:_
> macOS version 10.15.5（19F101）
> userscripts version 2.0.0
> Safari version 13.1.1（15609.2.9.1.2）

I saw an **iChat** _symbolic link_ under:
`~/Library/Containers/com.userscripts.macos.Userscripts-Extension/Data/Documents/`

linked to:
`../../../../../Documents/iChats`

I just want to ask if this _symbolic link_ is created by the extension or myself?

I suspect this is some weird files committed along with the app.

My computer is quite new so the **iChat.app** _never existed_ on my computer.

**Comment by quoid** [comment]
@ed9w2in6 

I am not sure why that symlink gets added, but it seems to get added for **all** extension (not just this one).

See my images below, both the [1password](https://github.com/1Password) extension from agilebits, the [Ka-Block](https://github.com/dgraham/Ka-Block) extension and pretty much every app and system service located in the `containers` folder add that symlink.

**Comment by ed9w2in6** [comment]
I can confirm thats true for _**every folder**_ under `~/Library/Containers` for me as well.

I ran this, can you try running it as well?:
```zsh
Containers USERNAME@HOSTNAME < zsh >[一  7 13 14:28:13 ]
(base)  •̀ω•́)⊃━ 急急如律令》% foobar | uniq -c
 304 yes
Containers USERNAME@ HOSTNAME < zsh >[一  7 13 14:28:20 ]
(base)  •̀ω•́)⊃━ 急急如律令》% ls | wc
     304     304   10519
Containers USERNAME@ HOSTNAME < zsh >[一  7 13 14:28:25 ]
(base)  •̀ω•́)⊃━ 急急如律令》% foobar() { 
for folders in $(ls); do
    if [[ -n $(ls "$folders//Data/Documents/iChats") ]]; then
        echo yes;
    else
        echo no;
    fi
done;
}
```

Thats the weirdest thing I have ever seen.
Feel free to _close this issue_ or can wait until _the reason is found out_.

The symbolic link is broken so I cant see its purpose.

Maybe a _Xcode_ thing?

**Comment by quoid** [comment]
Yeah it certainly weird, probably a relic from the past since. I am not sure I will ever find out why it's added 🤣 so I might as well close the issue
