### ISSUE TITLE
[Bug] `@run-at document-start` doesn't always run before the page load

### ISSUE THREAD

**Issue by redphx** [quoid/userscripts#529]
**Platform:**  
- OS: macOS 13.4
- Browser: Safari 16.5
- Userscripts 4.4.3

**Problem:**
`@run-at document-start` should run before anything else in the web page, but it doesn't.  
Users using Tampermonkey on other browsers don't have this bug.  

**Test code:**  
```js
// ==UserScript==
// @name         run-at bug
// @namespace    https://github.com
// @version      1.0
// @match        https://www.xbox.com/*/play*
// @run-at       document-start
// @grant        none
// ==/UserScript==

console.log('Userscripts - document-start');
```

Web page to test: https://xbox.com/play (but I think you can test on any sites)   

**Expected result:**  
<img width="425" alt="image" src="https://github.com/quoid/userscripts/assets/96280/9a699341-306b-4185-be72-ed53f1e9d8dc">

**What I got:**  
<img width="425" alt="image" src="https://github.com/quoid/userscripts/assets/96280/a9e22e66-79a5-4ee2-8bb9-817e65a67966">

The first time I load the page it works as intended. But after that, the script will only be injected after the page is loaded, which lead to unexpected errors.

**Comment by redphx** [comment]
Sorry I just checked the docs. Looks like this can't be fixed?  

<img width="704" alt="image" src="https://github.com/quoid/userscripts/assets/96280/5ed8061f-a657-40c7-87ac-7e1149236e5c">

**Comment by quoid** [comment]
@redphx Yeah, it's been a futile effort to try and beat the page load on Safari... *so far*.

**Comment by redphx** [comment]
Thanks. I'll find a way to work around this limitation. Good luck.

**Comment by redphx** [comment]
This is how I detect whether the script is executed before or after the page load.  

```js
var onLoadTriggered = false;
window.onload = () => {
    onLoadTriggered = true;
};

init();

// Userscript was loaded after the page loaded
if (document.readyState === 'complete' && !onLoadTriggered) {
    workaroundScripts();
}
