### ISSUE TITLE
BTTV Userscript does not work anymore with 2.0

### ISSUE THREAD

**Issue by CalleB69** [quoid/userscripts#53]
Hi, worked flawlessly with 1.5 but now it doesnt anymore. 

Here is the code: 
```
// ==UserScript==
// @name            BetterTTV
// @namespace       BTTV
// @description     Enhances Twitch with new features, emotes, and more.
// @copyright       NightDev, LLC
// @icon            https://cdn.betterttv.net/assets/logos/bttv_logo.png
//
// @grant           none
//
// @include         *://*.twitch.tv/*
//
// @version         0.0.2
// ==/UserScript==

(function betterttv() {
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = 'https://cdn.betterttv.net/betterttv.js';
    var head = document.getElementsByTagName('head')[0];
    if (!head) return;
    head.appendChild(script);
})()
```

hopefully you have some insight, i was only using userscripts for this! Thanks a lot!

**Comment by quoid** [comment]
@CalleB69 

Change `@include` to `@match`, see these issues:

https://github.com/quoid/userscripts/issues/45
https://github.com/quoid/userscripts/issues/46
https://github.com/quoid/userscripts/issues/47

**Comment by CalleB69** [comment]
> Change `@include` to `@match`, see these issues:

Awesome thanks so much for your great product, this fixed the issue! I will close this, hopefully it stays visible to anyone having the same issue!
