### ISSUE TITLE
Keep editor focus on save

### ISSUE THREAD

**Issue by MisterMediocre** [quoid/userscripts#60]
_System Information:_
> macOS version: 10.15.6 
> Userscripts version: 2.0.1
> Safari version: 13.1.2 (15609.3.5.1.3)

Once you save with cmd+s (and it successfully saves), the cursor dissapears, and you cannot continue typing without requiring a mouse click to get the cursor back. Would be great if this could be fixed, since I instinctively cmd+s every 10 secs, and have to keep using the mouse between typing. 

//also should add feature to add existing scripts directly, rather than having to copy paste to a new script file.

**Comment by quoid** [comment]
I will address with in the next update. I am going to tweak the title a bit to better reflect what is happening.

> //also should add feature to add existing scripts directly, rather than having to copy paste to a new script file.

Do you mean something like this?

> **Do I need to use the extension's editor to create new userscripts or to edit existing?**

> No; simply put your userscript in the extension's scripts folder. You can easily access this folder by clicking the link in the extension's settings modal option labelled "Save Location" or by visiting ~/Library/Containers/com.userscripts.macos.Userscripts-Extension/Data/Documents/scripts/.

**Comment by MisterMediocre** [comment]
> No; simply put your userscript in the extension's scripts folder. You can easily access this folder by clicking the link in the extension's settings modal option labelled "Save Location" or by visiting ~/Library/Containers/com.userscripts.macos.Userscripts-Extension/Data/Documents/scripts/.

Yeah this is what I meant. Thanks. But if I couldn't figure it out on my own, this is not a very intuitive solution. Maybe can have a button to choose file for upload, which is the standard solution everywhere else. Thanks.

**Comment by quoid** [comment]
Thanks for the feedback.

I recommend everyone looks at the documentation, especially when there is something they feel is missing. I tried my best to promote this, by including a persistent link int he sidebar.

At the moment I disagree with the idea that it is not intuitive to drag and drop files in location that you can open by clicking on a link in the settings. I think it would actually be *less* intuitive to have an "upload" area depending on the implementation and not a be a wise use of development resources when the current solution is so simple.

**Comment by quoid** [comment]
Thank you for the feedback.

I am not sure I agree with the sentiment, however I will keep it in mind for future updates.

**Comment by quoid** [comment]
resolved in [2.1.0](https://github.com/quoid/userscripts/releases/tag/v2.1.0)
