### ISSUE TITLE
Allow users to donate to the project

### ISSUE THREAD

**Issue by kubk** [quoid/userscripts#748]
Thank you for the project! It gives developers superpowers, and the ability to inject my own script has helped me a lot.

I wonder if there is a way to donate via GitHub Sponsors, PayPal, or crypto to show a little sign of appreciation. I've read the "Support" section in README and already left my review on AppStore but couldn't find anything related to sending money.

**Comment by quoid** [comment]
Thanks for the kind words @kubk. I think leaving a review is a **great** contribution to the project as it can inspire the contributors to keep doing the great work they do. I also think signing up to be a beta tester and helping shape the future of the app/extension is another great way to contribute. 

Currently the contributors of this project accept no monetary donations, but the sentiment is appreciated.

In the future this type of topic is better suited for the [discussions page](https://github.com/quoid/userscripts/discussions).
