### ISSUE TITLE
Error injecting script

### ISSUE THREAD

**Issue by nikolay-n** [quoid/userscripts#75]
Error injecting script after Safari update: "Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy." 

_System Information:_
> macOS version: 10.14.6
> Userscripts version: 2.1.1
> Safari version: 14.0 (14610.1.28.1.9)

**Comment by quoid** [comment]
@nikolay-n 

That error is relevant to the website's [content security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). The ability to inject javascript is dependent on the content security policy of the website where you want to inject. That is outside of the control of this extension or anyone beyond the website owner.

This extension will attempt a workaround if a strict CSP is detected and attempt another method of injection - however, you will **still** see this error in the console, even if the workaround was successful. If the fallback approach is used, context changes and certain things will not be possible - **[read this](https://github.com/quoid/userscripts/issues/39#issuecomment-643346939)** for more information.


**Can you please provide the url of the website in question *and* the code you are attempting execute?**

**Comment by quoid** [comment]
Here's a good example - `github.com` has a strict content security policy. It *does not* allow inline javascript. By default, this extension attempts to write inline javascript. This results in the code not executing.

Since 2.0, I made changes to detect security policy violations which utilizes a fallback method if this occurs. This can be demonstrated with the following userscript. Even though you see the error in the console, which is needed to trigger the fallback approach, the code *is still executed.*

Give it a try.

```js
// ==UserScript==
// @name        Strict CSP Demo
// @description This userscript will still execute on a website with a strict CSP - check your console to see the error
// @match       *://*github.com/*
// ==/UserScript==

alert("This worked, but you will still see any error in the console!");
```

**Comment by nikolay-n** [comment]
<img width="1426" alt="CleanShot 2020-09-17 at 19 44 12@2x" src="https://user-images.githubusercontent.com/59014332/93501706-7e359f80-f91e-11ea-9662-c6465e8c3110.png">
I've tried to figure out what's wrong and seems some logic before fallback eval method don't works like expected

**Comment by quoid** [comment]
@nikolay-n please provide the url of the website and the userscript (or shortened version), that will get us to the resolutions a lot quicker

**Comment by nikolay-n** [comment]
It's Google spreadsheet document https://docs.google.com/spreadsheets/d/...

```
// ==UserScript==
// @name        GoogleDocsExtensions
// @description Adds some features to Google Docs
// @match       https://docs.google.com/spreadsheets/d/*
// ==/UserScript==

console.log("Hello from script!");
```

**Comment by quoid** [comment]
Thanks! Give me a little to look into this - I assume any spreadsheet doc will work for testing

**Comment by quoid** [comment]
<img width="1258" alt="Screen Shot 2020-09-17 at 12 54 41" src="https://user-images.githubusercontent.com/7660254/93502676-07c87b80-f8e5-11ea-9269-ed0470ea4572.png">

Working as expected in macOS 10.15.6 - I am going to try with macOS  10.14.6 in a little.

**Comment by nikolay-n** [comment]
The script worked before Safari update

**Comment by quoid** [comment]
@nikolay-n 

I tested on 10.14.6 running Safari 14.0 and I am getting expected results, see image, below. Can you provide the following?

1) Can you please create a *new* script and keep the "universal" match pattern (`*://*.*`) and put a simple console.log in there to see if that works? Let me know if that log messages shows in a google spreadsheet.

2) Could you also take a screenshot of the userscript editor metadata with **invisibles** turned on? (example image below)

![Screen Shot 2020-09-17 at 1 32 53 PM](https://user-images.githubusercontent.com/7660254/93506993-0c902e00-f8eb-11ea-9ea7-53e12715c6ee.jpeg)

<img width="849" alt="Screen Shot 2020-09-17 at 13 40 20" src="https://user-images.githubusercontent.com/7660254/93507226-5d078b80-f8eb-11ea-99d4-80845d1c9ef8.png">

**Comment by nikolay-n** [comment]
using 
```
// ==UserScript==
// @name        TestScript
// @description This is your new userscript, start writing code
// @match       *://*.*
// ==/UserScript==

console.log("Hello there!")
```

on domain https://www.lipsum.com
<img width="672" alt="CleanShot 2020-09-17 at 20 50 40@2x" src="https://user-images.githubusercontent.com/59014332/93508776-7d553b80-f927-11ea-90ce-d742eaad8d53.png">

on google docs not works and variables has content
<img width="635" alt="CleanShot 2020-09-17 at 20 52 39@2x" src="https://user-images.githubusercontent.com/59014332/93509022-d3c27a00-f927-11ea-9201-8e4cb0222234.png">

on GitHub works and variables has other content
<img width="502" alt="CleanShot 2020-09-17 at 20 53 49@2x" src="https://user-images.githubusercontent.com/59014332/93509204-13896180-f928-11ea-8a90-b9a6a94a5f9b.png">

**Comment by quoid** [comment]
@nikolay-n 

how are you logging those `ext` and `src`??

**Comment by nikolay-n** [comment]
Breakpoint in Dev tools 

<img width="1038" alt="CleanShot 2020-09-17 at 21 00 11@2x" src="https://user-images.githubusercontent.com/59014332/93509736-d5407200-f928-11ea-97b8-f5193f30087c.png">

**Comment by nikolay-n** [comment]
Fix to this weird case (ext.startsWith(src) || src.startsWith(ext))

**Comment by quoid** [comment]
@nikolay-n I can't reproduce the issue - everything is working as intended on both 10.14.6 and 10.15.6 with safari 14 here

**Comment by nikolay-n** [comment]
Ok, thanks! I'm lucky man. I have to find a workaround for myself.

**Comment by quoid** [comment]
@nikolay-n 

I believe I was able to reproduce, a little more testing 

I will update you when i push fix

**Comment by nikolay-n** [comment]
> @nikolay-n
> 
> I believe I was able to reproduce, a little more testing
> 
> I will update you when i push fix

Thanks!!!

**Comment by quoid** [comment]
@nikolay-n 

I don't know why it took so long for me to experience the issue, but something did change in Safari 14. Specifically with the way `securitypolicyviolation` events are handled. The `event.sourceFile` string is different now, which was causing issue, *as you were suggesting in the comments*.

I implemented your fix from [here](https://github.com/quoid/userscripts/issues/75#issuecomment-694405606). It seems to work for me.

I will submit this build to the app store today, but you can download the build with the hotfix here. **Please** let me know asap if the hotfix resolved the issue. I'd like to know before I submit the build to the appstore.

[Userscripts.app.zip](https://github.com/quoid/userscripts/files/5241317/Userscripts.app.zip)

**Comment by nikolay-n** [comment]
@quoid All works!!! Thanks a lot!!!

**Comment by quoid** [comment]
@nikolay-n great! I will push it to the app store later today. I am going to close the issue now - feel free to leave a review on the app store :) that helps out a lot

**Comment by revolter** [comment]
> This can be demonstrated with the following userscript.

@quoid, That example doesn't work for me in Safari 14.0.1.

**Comment by quoid** [comment]
@revolter 

It shouldn't work any longer, the auto CSP detection was disabled by default. The user now has to explicitly set `@inject-into` and the valid values are `page`, `content` and `auto`. The default value is `page`. For a `github.com` page, use `content` or `auto`.

However, looks like there is some issues with `auto` on `github.com` right now, so use `content`. [Metadata reference](https://github.com/quoid/userscripts#userscript-metadata)

Example script, that is working for me on github, but on version 14.0:

```js
// ==UserScript==
// @name        Strict CSP Demo
// @description This userscript will still execute on a website with a strict CSP - check your console to see the error
// @match       *://*github.com/*
// @inject-into content
// ==/UserScript==

alert("Hello World!");
```

**Comment by quoid** [comment]
@revolter another note:

On one of my [website](https://www.filmgarb.com), `auto` works as intended, so I am not sure why it is not working properly on Github. If you visit my website using this userscript, it should work.

Please let me know if either of the above works for you.

```js
// ==UserScript==
// @name        Strict CSP Demo
// @description This userscript will still execute on a website with a strict CSP - check your console to see the error
// @match       *://*filmgarb.com/*
// @inject-into auto
// ==/UserScript==

alert("Hello World!");
```

**Comment by revolter** [comment]
`auto` actually works for me on GitHub, and so does `content`. What do you exactly mean by "there is some issues"? It doesn't work all the time?

**Comment by quoid** [comment]
> What do you exactly mean by "there is some issues"? 

I meant that for me, `auto` was not working, but `content` was.

I do not know why. On my website with a strict CSP, auto works fine.
