### ISSUE TITLE
Injection Timing Issue

### ISSUE THREAD

**Issue by quoid** [quoid/userscripts#79]
_System Information:_
> macOS version: 10.15.3
> Userscripts version: 2.2.0 beta
> Safari version: 13.0.5

Timing metadata seemingly not working @calmbit

related #78

**Comment by CalmBit** [comment]
The metablock for the must-run-first script (WOF) is the following:

```
// ==UserScript==
// @name        Wanikani Open Framework
// @namespace   rfindley
// @description Framework for writing scripts for Wanikani
// @version     1.0.52
// @include     /^https://(www|preview).wanikani.com//
// @copyright   2018+, Robin Findley
// @license     MIT; http://opensource.org/licenses/MIT
// @run-at      document-start
// @grant       none
// @weight 999
// ==/UserScript==
```

The metablock for the dependent script is the following:

```
// ==UserScript==
// @name         Wanikani Heatmap
// @namespace    http://tampermonkey.net/
// @version      2.0.26
// @description  Adds review and lesson heatmaps to the dashboard.
// @author       Kumirei
// @match        https://www.wanikani.com/
// @match        https://www.wanikani.com/dashboard
// @include      *preview.wanikani.com*
// @grant        none
// @weight 1
// @run-at document-end
// ==/UserScript==
```

**Comment by quoid** [comment]
Testing now, I will report back in a few

**Comment by CalmBit** [comment]
Just as a comment, the `@run-at document-start` seems to be being ignored, as it's just a couple tags above the dependent script in the DOM, near the end of the document.

**Comment by quoid** [comment]
> // @include     /^https://(www|preview).wanikani.com//

Is this attempting to target to all `www` and `preview` `wanikani.com` pages? or just the top level pages?

**Comment by CalmBit** [comment]
Upon checking Chrome w/ Tampermonkey, I can confirm it's targeting all pages under `www.wanikani.com` and `preview.wanikani.com`.

**Comment by quoid** [comment]
Ok, got ya.

I think the `@include` is part of the issue (or possibly the entire issue). `@include` isn't really supported by this extension, only as an alias for `@match`. Because of that, the ability to use regex patterns like `@include` did in a lot of other userscript managers *isn't* support. 

I am not sure when/if l will implement full `@include` support. I prefer `@match` since it's theorized [to be safer](https://stackoverflow.com/questions/31817758/what-is-the-difference-between-include-and-match-in-userscripts), but has some more restrictions. 

That being said, you can remove:

> // @include     /^https://(www|preview).wanikani.com//

and add:

> // @match       https://www.wanikani.com/*
> // @match       https://preview.wanikani.com/*

and it should work as expected, please let me know

**Comment by CalmBit** [comment]
Beautiful! Works like a charm now - thank you very much!

**Comment by quoid** [comment]
@CalmBit awesome, please let me know if you hit any other issues, I really wanna put these new metadata fields through the ringer!

**Comment by CalmBit** [comment]
Just some preliminary tests have at least confirmed that even the implementation of the `@run-at` token was enough to make the script run correctly by default - the weights seem to work just as intended, without and hangups at least with some small tests. I'm probably a pretty uncreative tester, but at the very least some simple tests prove pretty solid.

Quick note - dunno if it's intentional, but the upper bound for the weight actually seems to be 1000, at least with a preliminary test, haha. Both scripts at `document-start`, dependent at weight 999, WOF at weight 1000, and all works fine. 1001 however does not.

**Comment by quoid** [comment]
> Quick note - dunno if it's intentional, but the upper bound for the weight actually seems to be 1000, at least with a preliminary test, haha. Both scripts at document-start, dependent at weight 999, WOF at weight 1000, and all works fine. 1001 however does not.

Something weird going on with the weight after testing, I think it needs to be refined a bit more, thank you for pointing it out!

**Comment by CalmBit** [comment]
The `@weight` tag also seems to currently support negative numbers, with their absolute value being treated as their weight (i.e. -1 runs after -999) - plus, with negative numbers, the weight calculation is unbounded (-10000 runs after -999 without hesistation).

**Comment by quoid** [comment]
@CalmBit 

I did some more testing and I *think* it is working as intended. Some examples below - I am using https://www.k21p.com for testing since there is no strict CSP on my website and the assumption is that `@run-at` and `@inject-into` is the same.

**_a1.js**
```js
// ==UserScript==
// @name        _a1
// @description This is your new userscript, start writing code
// @match       *://*.*
// @weight 1
// ==/UserScript==

console.log("a1 weight is 1");
```

**_a2.js**
```js
// ==UserScript==
// @name        _a2
// @description This is your new userscript, start writing code
// @match       *://*.*
// @weight 1
// ==/UserScript==

console.log("a2 weight is 1");
```

Both of those scripts have the same weight, their execution time can vary between pages loads. For example `_a2.js` can load before `_a1.js`. Since their weight is equal injection time can be completely random.

---

**_a1.js**
`// @weight 5000`

**_a2.js**
`// @weight 1 `

Since `_a1.js` has a value that exceeds `999` it's value [is set to](https://github.com/quoid/userscripts/blob/05cad5afcfd43fc13ccdceb5bf6a445c771e5d99/extension/Userscripts%20Extension/Functions.swift#L84) `999`.

`_a1.js` *should* always be injected before `_a2.js`.

---

**_a1.js**
`// @weight 999`

**_a2.js**
`// @weight 1000 `

The same as above here for `_a2.js` - because its value exceeds `999` it is set to `999`. And due to this, `_a1.js` and `_a2.js` has the *same* weight so their loading times *can* be completely random or equally likely one will *always* load before the other, but that is happenstance, not because of their weight. It could happen that the one with `1000` weight is always/often loading before the one with `999`.

---

> (i.e. -1 runs after -999) 

The same goes for negative numbers - if `value < 1`, it becomes 1 and loading times can *seem* to be correlated to their weight but through my testing it is seemingly happenstance. I was running a test with those numbers and could not reproduce it *every* time. There were some times where `-999` ran first but other times `-1` ran first as shown below:

<img width="1266" alt="Screen Shot 2020-09-29 at 12 26 13" src="https://user-images.githubusercontent.com/7660254/94586285-08e79a00-024f-11eb-9b23-4acc6861f03f.png">

Although it does seem to be working as intended, I think more attention should be paid to weight. If you see a way to improve the weight normalize function, please do share.

**Comment by CalmBit** [comment]
Ahh, okay. Race conditions do seem pretty likely in this case, and that code _does_ seem like it'd be pretty fool-proof for making the weights obey the limits. My bad!

Continuing from the conversation in our other ticket - this might be a nice place for an editor hint, if that does end up getting implemented, or at least the debug console notification (i.e. "this weight is a fallback, not an actual acceptable weight")

**Comment by quoid** [comment]
closing this issue as it seems weight is working as intended
