### ISSUE TITLE
Make adjustments to pass App Store Review

### ISSUE THREAD

**Issue by quoid** [quoid/userscripts#8]
v1 pass review, here's why:

> ## Design Preamble

> The user interface of your app is not consistent with the macOS Human Interface Guidelines.

> **Specifically, we found that when the user closes the main application window there is no menu item to re-open it.**

> ### Next Steps

> It would be appropriate for the app to implement a Window menu that lists the main window so it can be reopened, or provide similar functionality in another menu item. macOS Human Interface Guidelines state that "The menu bar [a]lways contains [a] Window menu".

> Alternatively, if the application is a single-window app, it might be appropriate to save data and quit the app when the main window is closed.

> For information on managing windows in macOS, please review the following sections in Apple Human Interface Guidelines:

> * The Menu Bar and Its Menus
> * The Window Menu
> * The File Menu
> * Clicking in the Dock
> * Window Behavior

> Please evaluate how you can implement the appropriate changes, and resubmit your app for review.

**Comment by quoid** [comment]
- figure out what the message means
- remove extraneous menu items (help, hide, etc...)
  - the only neccessary menu items are `About Userscripts` and `Quit Userscripts`

**Comment by gingerbeardman** [comment]
I guess alternative is to wait app on window close?

**Comment by quoid** [comment]
@gingerbeardman I am hoping to get some further clarity from Apple, but from doing some web searches it seems the issues is that *when a user closes the main app window, there now way to bring it back*.

An example would be that when you have a Mac App open, and you hit `command+w` to dismiss the main app window. With some apps, like Spotify for example, there's a menu item called window where the user can click the `Spotify` menu item to bring back the window (or they can click the app icon in the dock) - screenshot below.

<img width="157" alt="Screen Shot 2019-05-13 at 12 54 46 PM" src="https://user-images.githubusercontent.com/7660254/57639885-f2b83b80-757e-11e9-8693-8d4c390536e5.png">


I don't think that functionality is enabled by default - some apps don't have it (example: [Ka-Block!](https://github.com/dgraham/Ka-Block)). If the user dismisses main app window (which doesn't do much, just like Userscripts main app window), the only way to get it show up again is by quitting the app and restarting it. I believe this the behavior that Apple is trying to avoid.

To resolve this, I believe a couple of approaches can be taken:

1) Programmatically quit the app when the last window is closed - [method](https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428381-applicationshouldterminateafterl)
2) Implement a `Window` menu item like Spotify does and/or implement the behavior where if the window is closed/dismissed, clicking the app icon shows it again.

The **problem** I am encountering is that there is no way for me to test this, that I am aware of. The main app window in Userscripts is seemingly *not* able to be dismissed/closed. `Command+W` does not dismiss the main app window, hitting the `X` button does not dismissed the main app window and there is no *Title Bar* with close, minimize and zoom buttons. So I am not even sure how to test this.

Do you know of alternate ways of dismissing an application window, other than the methods mentioned above? 

I followed up with Apple to see how they are dismissing the Userscripts window - it's seems kind of silly to make the main app window able to be dismissed/closed, just to implement functionality that makes it appear once dismissed.

**Comment by quoid** [comment]
In reality, it's probably easiest and least time consuming to  just to do what you recommended - quit the app on window close.

**Comment by quoid** [comment]
made the changes in https://github.com/quoid/userscripts/commit/ee0360b5b30dd3f3e01529231285a6a76b3126db , but keeping the issue open until accepted into the store in the likely case something else blocks acceptance :)

**Comment by quoid** [comment]
Passed and on App Store - [link](https://itunes.apple.com/us/app/userscripts/id1463298887)

**Comment by gingerbeardman** [comment]
Congrats!
