### ISSUE TITLE
@require Metablock tag

### ISSUE THREAD

**Issue by CalmBit** [quoid/userscripts#80]
This is obviously a hilariously and unreasonably insecure request, given that it's essentially side loading scripts based on arbitrary metadata, but I'll ask anyway - are there any plans to support `@require` in metablocks? 

I have a script that, predictably, `@require`s a version of JQuery. I could (probably) just turn this into a separate userscript, if necessary, but it's definitely not the most obvious failure, so if the tag isn't planned to be supported, is there a chance that the editor could warn on the use of unsupported metablock tags? Might be a bit much to ask, but also might save a bit of work wrt. "my script is broken????" in the future.

Thanks again 😄

**Comment by quoid** [comment]
There's been a few requests for `@require` support. I don't have *immediate* plans to implement it and in general I have some ambivalent feelings towards that tag, one of which you alluded to (insecure). 

It **would** be a good idea to alert users about unsupported tags though. I see a couple of ways this could be implemented, but this might be the "easiest":

Implement the [parser](https://github.com/quoid/userscripts/blob/14b59c49fd4751c7ea3fae3a7bdf59dcd1c81314/src/js/dev.js#L201) form the development js into the production app. When the user saves a script, log any unsupported metadata tags to the browser console in a warning. Maybe show a message in the status area (bottom left) of the editor on save if it *did* log this kind of error.

What are your thoughts on implementation of this?

**Comment by CalmBit** [comment]
I think the parser to console errors would be a good solution, although a status message would definitely bring it to being fully user-friendly. Assumably most users who are tampering with Javascript are reasonably able to access the console, but if this isn't the case for any reason, some visual, non-technical indicator might be wise.

**Comment by quoid** [comment]
I believe metadata tags can be linted in the codemirror instance, so that would provide a user friendly way of alerting users of unsupported tags. Currently linting is disabled, I started working on it but never fully implemented it.

I would aim for next minor release after 2.2.0.

**Comment by CalmBit** [comment]
Sounds good to me! A linting system in general sounds like a reasonably good idea 😄

**Comment by maxgarber** [comment]
Just seconding the desire for `@require` -- or some other direct way of declaring dependencies between separate (local) scripts, maybe even enabling ES6 modules or something. 

The use-case I'm imagining is: I have a basic set of declarations in one file, and depend on/extend them in another. The `@weight` just added (thanks!) does enable this, but it means managing the weight values manually, but it'd be lovely to just say in script x that it depends on script y.

**Comment by quoid** [comment]
@maxgarber my experience with other userscript managers is limited to mostly violentmonkey for FF, but as far as I am aware `@require` is for remote sources, or relative sources to a remote script, not local files. The reason I point this out is because it doesn't seem like `@require` would enable the type of behavior you're after in your use case.

I very much like the idea of creating a new tag to enable what you've outlined. I think it would be very useful. The idea would need to be fleshed, if you're interested we can talk over email about it.

**Comment by CalmBit** [comment]
Although this comment might fit better in #83, it would be interesting to have a `@require` analogue that, by default, only responds to `file://` URIs. It may make it easier to include things like script dependencies that would otherwise clutter the userscript interface. 

Alternatively, perhaps as a compromise towards a more "universal" approach (i.e. if `@require` was ever to be implemented for compatibility), the plugin could do something like confirm with the user that the dependency the script requires should be downloaded/queried? Just spitballing this idea here in case it makes any sense or helps to formalize a better system for those kinds of remote dependencies.

**Comment by quoid** [comment]
@CalmBit I think you're right, that this comment is better suited for #83 - I am going to move it there and respond in that thread

**Comment by revolter** [comment]
I, too, want to use a common file that's uploaded on GitHub from multiple scripts.

**Comment by quoid** [comment]
@revolter This is planned for the next major release. I can not give an exact time frame when v3.0.0 will be complete, but I am actively working on it and **hope** it will be released within 2 months.

**Comment by quoid** [comment]
done in https://github.com/quoid/userscripts/commit/c195001f32019bde0eafaae35ff12af9e384a4f2
