### ISSUE TITLE
Is it possible to run a script in an iframe?

### ISSUE THREAD

**Issue by michaelmesser** [quoid/userscripts#86]
Is it possible to run a script in an iframe? It does not trigger for me but it works when the page is not in a frame.

_System Information:_
> macOS version: 10.14.6
> Userscripts version: 2.2.0
> Safari version: 14.0.1

**Comment by quoid** [comment]
@michaelmesser 

Are you running into into issues with this?

It theoretically should run in an iframe if the `@match` pattern matches to the iframe's source.

If you provide an example page, I can take a look and see if this is functioning properly.

**Comment by michaelmesser** [comment]
@quoid Your message disappeared. But as far as I can tell https://github.com/quoid/userscripts/blob/master/extension/Userscripts%20Extension/UserscriptsSafari.js#L126 blocks it from working on an iframe. The page I am working with is not public facing so I cannot use it as an example.

**Comment by quoid** [comment]
@michaelmesser 

Ninja edit:

It is not currently possible. You can [see this line](https://github.com/quoid/userscripts/blob/master/extension/Userscripts%20Extension/UserscriptsSafari.js#L126) of code for why it doesn't happen.

Essentially every script has the `@noframes` option.

**Comment by quoid** [comment]
I remove my original message because it was incorrect. Your are correct, that's why it won't work.

I can make the `@noframes` an actual option in the next update. It will be several weeks before the next update, I am working on v3.0.0 right now.

**Comment by michaelmesser** [comment]
After removing the check for the top window the following changes are needed:
In [JavaScript](https://github.com/quoid/userscripts/blob/master/extension/Userscripts%20Extension/UserscriptsSafari.js#L128-L164)

```js
if (event.name === "RESP_USERSCRIPTS" && window.location.href === event.message.url) {
```
```js
safari.extension.dispatchMessage("REQ_USERSCRIPTS", {"url": window.location.href});
```

In [Swift](https://github.com/quoid/userscripts/blob/master/extension/Userscripts%20Extension/SafariExtensionHandler.swift#L12-L24)
```swift
let url = userInfo?["url"] as? String
```
```swift
respData["url"] = url;
```

This works for my use case. It is probably possible to the url to change without reloading and the changes above do not support that. I don't have time to polish it.

**Comment by quoid** [comment]
@michaelmesser 

In order to allow for iframe script injection, we really only need to remove that check linked above. Once that is removed, the `@noframes` key needs to be implemented. I haven't fully figured out how the implementation would look, but I reckon when returning scripts for injection it'd check for `@noframes` scripts and they'd pass through a different injection method (which would have the `window.top` check that was removed universally).

**Comment by michaelmesser** [comment]
@quoid I believe that the Swift file currently get the *page* url not the *frame* url. So passing the frame url in the message is needed. I could be wrong.

**Comment by quoid** [comment]
@michaelmesser you are right. 

The injected script (UserscriptsSafari.js ) sends a request to the swift side asking for the code from the indiv. userscripts. The swift side checks the page url, rather than it being sent from the injected script.

What you are saying makes sense, I guess we would need the injected script send along the window.location when it is requesting code and the swift side can use that to location which userscripts should be loaded.

Maybe when the injected script gets the response, `RESP_USERSCRIPTS`, it can send along that page url (the one that is currently being used to get userscripts) and we can use *that* as a "`window.top`" check - for userscripts that have the `@noframes` key.

Does that make sense to you?

**Comment by quoid** [comment]
> Maybe when the injected script gets the response, RESP_USERSCRIPTS, it can send along that page url (the one that is currently being used to get userscripts) and we can use that as a "window.top" check - for userscripts that have the @noframes key.


Looking back at your other comment, it seems like I just repeated what you wrote here:

> `let url = userInfo?["url"] as? String`
> `respData["url"] = url;`

**Comment by michaelmesser** [comment]
@quoid 
I think the best strategy is:

- JavaScript sends a request for the scripts with window.location.href and a unique id
- Swift sends a response with the scripts that should run based on that url and includes the unique id in the response
- JavaScript filters responses based on the unique id
- If a script has `@noframes` only run it if `window.top === window`

**Comment by michaelmesser** [comment]
I am not sure how to handle the unique id yet.

**Comment by quoid** [comment]
That seems like a good strategy. 

> Also if there is more than one iframe with the same url, it will inject into each page twice.

I assume you are suggesting to include a unique id to prevent this?

**Comment by michaelmesser** [comment]
Yes. There is no need to send a url in the Swift to JS message. Just the unique id.

**Comment by quoid** [comment]
> I am not sure how to handle the unique id yet.

I have not tested anything yet, but couldn't we just save a uniqueId locally when dispatching `REQ_USERSCRIPTS` and pass it along with the request. When sending a response, pass along the uniqueId that was sent with the request for matching.

If a webpage has an iframe, there's 2 page/window contexts, each one of them will send a request. Each one of them will also receive 2 responses, but only execute on one of them - the one that matches the local uniqueId.

**Comment by michaelmesser** [comment]
@quoid Yes

**Comment by quoid** [comment]
@michaelmesser 

cool, this is slated for new major release, #87

**Comment by quoid** [comment]
@michaelmesser going to close this issue, we can continue the conversation in #87 

thank you again for helping out here

**Comment by quoid** [comment]
@michaelmesser 

I wanted to let you know that I've implemented the ability to run scripts in frames on the `v3.0.0` branch. This addition aligns with other mainstream userscript editors. By default, script will run in frames, if the script contains the `@noscript` tag, it will **not**.

Using your your suggestions, this is how it works:

- content script send a request for code on page load, sending with it a unique id, the href and a bool indicating whether or it (the requester) is `window.top`
- once the swift "backend" gets this request, it run an updated `getCode` function
- whilst looking for scripts that have `@match` patterns that match the current url, it checks if script matches have the `@noframes` key
    - if script contains `@noframes` and the requester is *not* `window.top`, that file is ignored
- when all code is gotten, the swift side sends the response, which includes the code and the uniqueId that was sent by the requester
- when the content script gets the response it checks the id that was sent along with it against it's uniqueId and if there is a match, it executes the code as usual

I think that's it. It was much easier to implement than I thought. I have yet to thoroughly test it out, but I wanted to let you know the status.

Thanks again.
