### ISSUE TITLE
@version, @updateURL, @downloadURL functionality

### ISSUE THREAD

**Issue by babariviere** [quoid/userscripts#88]
It would be a nice feature to update scripts using the `@updateURL` tag.

Here is some documentation from Tampermonkey: https://www.tampermonkey.net/documentation.php#_updateURL

_System Information:_
> macOS version: 11.0.1
> Userscripts version: 2.2.0
> Safari version: 14.0.1

**Comment by quoid** [comment]
@babariviere 

I agree. Hopefully this can get implemented around the same time as `@require`. However I dont have an estimate on when this will happen.

**Comment by quoid** [comment]
done in https://github.com/quoid/userscripts/commit/e3f3ec92342c741ea69115586b6346ae0bd93619
