### ISSUE TITLE
Universal build for arm64/Apple Silicon

### ISSUE THREAD

**Issue by gnattu** [quoid/userscripts#91]
_System Information:_
> macOS version: macOS 11.0.1
> Userscripts version: 2.2.0
> Safari version: 14.0.1

Userscript currently only has x86 binaries, but the code compiles on arm.

**Comment by quoid** [comment]
Will try to push a new build for ARM tomorrow

**Comment by quoid** [comment]
built and pushed, submitted to app store on `2020-06-12`
